### ISSUE TITLE
Routing Key Generation

### ISSUE THREAD

**Issue by ronald-d-rogers** [pardahlman/RawRabbit#106]
Our message type would be an interface that can be seriailized/deserialized into many different types. For our purposes we need more granular control over how the routing key is generated, basically we need it to be {routing-key}.{type}. I don't see any way to do this currently. I'm thinking a `Func<Guid, Type, string>` passed in via configuration would do the trick. The delegate could accept both a Guid for the global request id and type. Perhaps a default `RoutingKeyProvider` could be wired up as well, which the delegate would override upon configuration, or perhaps it could be made a convention somewhere.

Are you ok with this? Is there any particular way you would prefer it implemented if so?

**Comment by pardahlman** [comment]
@ronald-d-rogers thanks for reporting this. Could you give me a bit more detailed explanation of your scenario? Do you mean that you explicit use an interface when publising a message like this

```csharp
var msg = new InterfacedMessage();
await client.PublishAsync<IInterfacedMessage>(msg);
```
or that you subscribe to messages with interface
```csharp
client.SubscribeAsync<IInterfacedMessage>(async (message, context) =>
{
	/* body here */
});
```
If you're subscribing to an interface, but want type-specific message handlers, it would make more sense to have multiple subscribers for the different types.

Have you tried the option to use the optional configuration builder upon publish/subscribe?
```csharp
client.SubscribeAsync<IInterfacedMessage>(async (message, context) =>
{
	/* body here */
}, cfg => cfg.WithRoutingKey("IInterfacedMessage.InterfacedMessage"));
```
```csharp
await client.PublishAsync<IInterfacedMessage>(msg, configuration: cfg => cfg
	.WithRoutingKey("IInterfacedMessage.InterfacedMessage"));
```

**Comment by pardahlman** [comment]
(If you're interested in contributing, you can follow the guide lines here http://rawrabbit.readthedocs.io/en/master/contributing-guidelines.html if it isn't to much work for you, you could create a PR and we can discuss it there.

**Comment by ronald-d-rogers** [comment]
Sorry I was on vacation.
I encountered the problem while trying to publish so my problem pertains to the first example you gave.  The interfaced message being published must be done so using a routing key based on the underlying type of the interface. I actually went through the code and the problem turned out to be more complicated than anticipated, and there were a few other things this library was missing that we needed so at this point we've decided to go the original route and roll our own.

**Comment by shahabganji** [comment]
@pardahlman 

I can't find ```.WithRoutingKey``` method, I am using following packages:

```xml
<PackageReference Include="RawRabbit" Version="2.0.0-rc5" />
<PackageReference Include="RawRabbit.Operations.Subscribe" Version="2.0.0-rc5" />
```

and part of my method: 

```cs
Action<ISubscribeContext> context = (ctx) => {
	ctx.UseSubscribeConfiguration(config => {
		config
                .FromDeclaredQueue(q => q.WithName("sample"))
		.OnDeclaredExchange(exch=> exch.WithName("sample"))
		;
	});
};

bus.SubscribeAsync<string>(async(payload)=> {
		logger.Information("A message received: {@Payload}" , payload);
	}, context);
```

anything missing here?

**Comment by shahabganji** [comment]
I found it, the context should be like this: 

```cs
Action<ISubscribeContext> context = (ctx) => {
	ctx.UseSubscribeConfiguration(config => {
		config
                .Consume(cns => cns.WithRoutingKey("test"))
		.FromDeclaredQueue(q => q.WithName("sample"))
		.OnDeclaredExchange(exch => exch.WithName("sample"))
		;
	});
};

bus.SubscribeAsync<string>(async(payload)=> {
   logger.Information("A message received: {@Payload}" , payload);
}, context);
```
