### ISSUE TITLE
Question: Producer & Consumer in same application

### ISSUE THREAD

**Issue by jayrulez** [pardahlman/RawRabbit#110]
Can I have the producer and the consumer running in the same asp.net core application?

**Comment by pardahlman** [comment]
@jayrulez yes! In fact, that is the setup in [most of the integration tests](https://github.com/pardahlman/RawRabbit/blob/stable/test/RawRabbit.IntegrationTests/SimpleUse/PublishAndSubscribeTests.cs#L162).

**Comment by jayrulez** [comment]
@pardahlman Would I set up the subscribers in the Configure method of the Startup class?

**Comment by pardahlman** [comment]
I apparently was a bit to quick to answer your question 😄 . I've never tried setting up a consumer in a ASP.NET Core app, but as long as the thread on which the consumer is set up is long running you should be fine. I guess I would hook it up in `Startup.cs`. Doesn't this work for you?

**Comment by pardahlman** [comment]
What is your scenario, btw? The normal use of a ASP.NET application would be to act on incoming requests and produce a response. The only other scenario I can think of is web sockets, and in those scenarios I've previously used `IRegisteredObject` (not sure if there is a .NET Core equalent to that)

**Comment by jayrulez** [comment]
I started wrapping RabbitMq.Client before coming across RawRabibt.

This is what I did.

I created a wrapper for publishing  messages too a queue or exchange.

    public class RabbitMqService : IMessageQueueService
    {
        private readonly IOptions<RabbitMqServiceOptions> Options;
        private readonly ILogger logger;
        private ConnectionFactory factory;

        public RabbitMqService(IOptions<RabbitMqServiceOptions> options, ILoggerFactory loggerFactory)
        {
            this.Options = options;
            this.logger = loggerFactory.CreateLogger<RabbitMqService>();

            this.factory = new ConnectionFactory()
            {
                HostName = Options.Value.HostName,
                UserName = Options.Value.UserName,
                Password = Options.Value.Password,
                VirtualHost = Options.Value.VirtualHost,
                Port = Options.Value.Port
            };

        }

        public Task PublishMessage<T>(QueueMessage<T> message, string queueName)
        {

            using (var connection = this.factory.CreateConnection())
            using (var channel = connection.CreateModel())
            {
                channel.QueueDeclare(queue: queueName,
                                     durable: true,
                                     exclusive: false,
                                     autoDelete: false,
                                     arguments: null);

                string serializedMessage = JsonConvert.SerializeObject(message);
                var body = Encoding.UTF8.GetBytes(serializedMessage);

                var properties = channel.CreateBasicProperties();
                properties.Persistent = true;

                channel.BasicPublish(exchange: "",
                                     routingKey: queueName,
                                     basicProperties: properties,
                                     body: body);

                this.logger.LogDebug($"Sent {serializedMessage} to queue '{queueName}'.");
            }

            return Task.FromResult(0);
        }

        public Task PublishBroadcastMessage<T>(QueueMessage<T> message, string exchangeName)
        {
            using (var connection = this.factory.CreateConnection())
            using (var channel = connection.CreateModel())
            {
                channel.ExchangeDeclare(exchange: exchangeName, type: "fanout");

                string serializedMessage = JsonConvert.SerializeObject(message);
                var body = Encoding.UTF8.GetBytes(serializedMessage);

                channel.BasicPublish(exchange: exchangeName,
                                     routingKey: "",
                                     basicProperties: null,
                                     body: body);

                this.logger.LogDebug($"Sent {serializedMessage} to exchange: '{exchangeName}'.");
            }

            return Task.FromResult(0);
        }

        public Task PublishDirectMessage<T>(QueueMessage<T> message, string exchangeName, string routingKey)
        {
            using (var connection = this.factory.CreateConnection())
            using (var channel = connection.CreateModel())
            {
                channel.ExchangeDeclare(exchange: exchangeName, type: "direct");

                string serializedMessage = JsonConvert.SerializeObject(message);
                var body = Encoding.UTF8.GetBytes(serializedMessage);

                var properties = channel.CreateBasicProperties();
                properties.Persistent = true;

                channel.BasicPublish(exchange: exchangeName,
                                     routingKey: routingKey,
                                     basicProperties: properties,
                                     body: body);

                this.logger.LogDebug($"Sent {serializedMessage} to exchange: '{exchangeName}' with routingKey: '{routingKey}'.");
            }

            return Task.FromResult(0);
        }

        public Task PublishTopicMessage<T>(QueueMessage<T> message, string exchangeName, string routingKey)
        {
            using (var connection = this.factory.CreateConnection())
            using (var channel = connection.CreateModel())
            {
                channel.ExchangeDeclare(exchange: exchangeName, type: "topic");

                string serializedMessage = JsonConvert.SerializeObject(message);
                var body = Encoding.UTF8.GetBytes(serializedMessage);

                var properties = channel.CreateBasicProperties();
                properties.Persistent = true;

                channel.BasicPublish(exchange: exchangeName,
                                     routingKey: routingKey,
                                     basicProperties: properties,
                                     body: body);

                this.logger.LogDebug($"Sent {serializedMessage} to exchange: '{exchangeName}' with routingKey: '{routingKey}'.");
            }

            return Task.FromResult(0);
        }

I then created a class to consume messages from a particular queue:

    public class EmailMessageHandler : QueueMessageHandler
    {
        private readonly IOptions<RabbitMqServiceOptions> Options;
        private readonly ILogger logger;
        private ConnectionFactory factory;

        const string ExchangeName = "email";
        const string QueueName = "email";
        const string RoutingKey = "email";

        public EmailMessageHandler(IOptions<RabbitMqServiceOptions> options, ILoggerFactory loggerFactory)
        {
            this.Options = options;
            this.logger = loggerFactory.CreateLogger<RabbitMqService>();

            this.factory = new ConnectionFactory()
            {
                HostName = Options.Value.HostName,
                UserName = Options.Value.UserName,
                Password = Options.Value.Password,
                VirtualHost = Options.Value.VirtualHost,
                Port = Options.Value.Port
            };
        }

        public void RegisterConsumer()
        {
            using (var connection = this.factory.CreateConnection())
            using (var channel = connection.CreateModel())
            {
                channel.ExchangeDeclare(exchange: ExchangeName,
                                        type: "direct");

                channel.QueueDeclare(queue: QueueName, durable: true, exclusive: false, autoDelete: false, arguments: null);


                channel.QueueBind(queue: QueueName,
                                  exchange: ExchangeName,
                                  routingKey: RoutingKey);

                this.logger.LogDebug($"QueueName: {QueueName}, ExchangeName: {ExchangeName}, RoutingKey: {RoutingKey}.");

                var consumer = new EventingBasicConsumer(channel);
                consumer.Received += (model, eventArgs) =>
                {
                    try
                    {
                        var body = eventArgs.Body;
                        var message = Encoding.UTF8.GetString(body);
                        var routingKey = eventArgs.RoutingKey;

                        this.logger.LogError($"Message received: {message}, RoutingKey: {routingKey}.");

                        Console.WriteLine(message);

                        channel.BasicAck(deliveryTag: eventArgs.DeliveryTag, multiple: false);
                    }
                    catch (Exception ex)
                    {
                        this.logger.LogError(ex.Message);

                        channel.BasicNack(deliveryTag: eventArgs.DeliveryTag, multiple: false, requeue: false);
                    }
                };

                channel.BasicConsume(queue: QueueName,
                                     noAck: false,
                                     consumer: consumer);
            }
        }

In the Startup.cs file I registered the handler as a service:

services.AddSingleton<EmailMessageHandler, EmailMessageHandler>();

in the Configure method I "registered" the handler

var emailMessageHandler = app.ApplicationServices.GetRequiredService<EmailMessageHandler>();

            emailMessageHandler.RegisterConsumer();

However, the consumer code runs  as far as I  can see. Nothing is removed fro the queue nor is anything in the logs from  the consumer code.

RawRabbit looks much nicer than what I wrote and I would like to utilize it.

I'm essentially want to use it as a background processor.

REST endpoints will perform required tasks then publish a message so a consumer will perform other processes not necessary for the response.

e.g:

User A requests 0.5 BTC from  User B:
The api endpoint will insert data into a request table then publishes a NewRequest message.

Several consumers will listen for these messages and perform tasks:

Send notifications to User B (SMS, Email, Push)
Insert an activity in the feed for both users.
Check whether the users are contacts or not and create a contact relationship if they are not.
Push the data to web socket for a live ticker.
etc...

Ideally, these tasks should be separate micro-services. However, at the stage we are now with the project, we are not ready to manage the type of infrastructure 10s of micro-services requires.

We would like to keep the consumers running in the api project for now and move them out as necessary for scaling in the future.

I'm gonna set up a quick test project to see how far RawRabbit can take me with this.

**Comment by pardahlman** [comment]
Right - I got you! So, you should be able to use RawRabbit and wire up your consumers in `Startup.cs`, just as you proposed. I (locally) modified the [https://github.com/pardahlman/RawRabbit/tree/stable/sample](sample projects) so that I called this method from the constructor

```csharp
private void SetupSubscriber()
{
	//TODO: resolve busClient from IoC
	var busClient = vNext.BusClientFactory.CreateDefault();
	busClient.SubscribeAsync<AnotherMessage>((message, context) =>
	{
		/* do stuff */
		return Task.FromResult(true);
	});
}
```
And then published a message when recieving the value request
```csharp
private static Task<ValueResponse> SendValuesThoughRpcAsync(ValueRequest request, MessageContext context)
{
	_client.PublishAsync(new AnotherMessage());
	return Task.FromResult(new ValueResponse
	{
		Value = $"value{request.Value}"
	});
}
```
With this setup the message handler registered in the ASP.NET Core app was called. Hope this helps!

**Comment by jayrulez** [comment]
So I set up this toy project to play with RawRabbit.

It works as desired so far.

However, i still have a few questions. 

How can I do acknowledgements with this setup?

Is there a way to pass a service (registered in the default container) to the subscriber to do the consuming?

**Comment by pardahlman** [comment]
Some of the answers you're looking for could probably be found in the [documentation](http://rawrabbit.readthedocs.io).

By default `RawRabbit` performs a basic ack when you've processed the message in the message handler. By using the advanced message context you the ability to [nack messages](https://github.com/pardahlman/RawRabbit/blob/stable/test/RawRabbit.IntegrationTests/Features/NackingTests.cs) in the message handler, [re-add the message to the queue with delay](https://github.com/pardahlman/RawRabbit/blob/stable/test/RawRabbit.IntegrationTests/Features/RetryWithDelayTests.cs) and other things.

We're using [Message Sequences](http://rawrabbit.readthedocs.io/en/master/message-sequence.html) in our REST api's. Might be something worth looking into for your solution!

How you solve your IoC setup is up to you. The subscriber can use classes from it's parent context/class.

**Comment by jayrulez** [comment]
How can I register rawrabbit with an AdvancedMessageContext in a vNext application using the config section from appsettings.json?

I'm trying this:

			services
				.AddRawRabbit<AdvancedMessageContext>(
					cfg => cfg.AddJsonFile("rawrabbit.json"),
					container => { 
                        container.AddSingleton(LoggingFactory.ApplicationLogger);
                    })
				.AddSingleton<IConfigurationEvaluator, AttributeConfigEvaluator>()
				.AddMvc();

However, I'm getting an error that the call is ambiguous.

**Comment by jayrulez** [comment]
Interestingly, when I close the running asp.net core application the dotnet process seems to keep running in the background indefinitely. See the latest code here:

https://github.com/jayrulez/Hutch

**Comment by jayrulez** [comment]
This is working pretty nicely now so I will close this issue. Thank you @pardahlman for your help.
