### ISSUE TITLE
Guard against OperationInteruptedException in TopologyProvider

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/RawRabbit#111]
If the `TopologyProvider` has items in its worker queue that is wrongly configured with respect to topology feature (auto delete, durable, etc.) the worker throws an exception and the worker is still in "work mode", even though no work is being done.

**Comment by jayrulez** [comment]
Ran into this just now while testing

**Comment by pardahlman** [comment]
The fix for this will be released within the week 👍

**Comment by pardahlman** [comment]
Commit ` 	a177237` fixes this issue
