### ISSUE TITLE
Connection to rabbitmq-server lingers

### ISSUE THREAD

**Issue by jayrulez** [pardahlman/RawRabbit#113]
So I'm not sure if this is a genuine issue or it just happens because of how I'm using RawRabbit.

However, when I close an asp.net core application using  ctrl + C, a connection to the rabbitmq-server still exists and the dotnet process keeps running in the background.

I either have to kill the  process manually from terminal or close the connection from the rabbitmq server.

The issue shows up running this toy application:

https://github.com/jayrulez/Hutch

Use ctrl + c to kill the application then look at the list of running processes and also look at the connections from the management console.

**Comment by pardahlman** [comment]
There could be a few reasons for this. From the top of my mind, it could be that you have an task running somewhere that is locking up the resource (connection). I tried to reproduce this on my normal .NET Core Console App, but everything shut down as expected. It could perhaps have to do with lifetime management of the ASP.NET application.

**Comment by jayrulez** [comment]
I will investigate this and let you know what I find.

**Comment by jayrulez** [comment]
So changing from using RawRabbit.Extensions.Client.IBusClient to using RawRabbit.IBusClient seems to solve this problem and the connection to the rabbitmq server terminates when I close the asp.net core console application.

```
      The consumer with tag 'amq.ctag-Vq7DbyItbFjP2AlAzJYL9A' has been cancelled.
info: EventingRawConsumer[0]
      Consumer amq.ctag-Vq7DbyItbFjP2AlAzJYL9A has been shut down.
        Reason: 
        Initiator: Application
        Reply Text: Connection close forced
dbug: EventingRawConsumer[0]
      The consumer with tag 'amq.ctag-tLjmPBpkJKlA522tIhqUVA' has been cancelled.
info: EventingRawConsumer[0]
      Consumer amq.ctag-tLjmPBpkJKlA522tIhqUVA has been shut down.
        Reason: 
        Initiator: Application
        Reply Text: Connection close forced
```

**Comment by pardahlman** [comment]
Ah! Thanks for the finding! I'll look into the disposal of `RawRabbit.Extensions.Client.IBusClient`
