### ISSUE TITLE
Using AdvancedMessageContext

### ISSUE THREAD

**Issue by jayrulez** [pardahlman/RawRabbit#114]
I tried to add RawRabbit with advanced message context like:

services
				.AddRawRabbit<AdvancedMessageContext>(
                    config => config.SetBasePath(_rootPath)
                        .AddJsonFile("rawrabbit.json"),
					container => { 
                        container.AddSingleton(LoggingFactory.ApplicationLogger);
                    })
				.AddSingleton<IConfigurationEvaluator, AttributeConfigEvaluator>()

However, I cannot get IBusClient<AdvancedMessageContext> from the container after.

I can hwoever, see IBusClient<MessageContext> in the container as well as BaseBusContext<MessageContext>

This seems weird as I would expect the bus client to be of type IBusClient<AdvancedMessageContext> or  BaseBusClient<AdvancedMessageContext> after adding RawRabbit with AdvancedMessageContext generic parameter.

**Comment by pardahlman** [comment]
The normal bus client uses `MessageContext`, if you want to use any other context type you need to say so explicitly
```csharp
services.AddRawRabbit<AdvancedMessageContext>()
``` 
You could create your own message context with domain specific properties, read more about that here http://rawrabbit.readthedocs.io/en/master/understanding-message-context.html.

If you register the bus client with a custom context, you need to either wrap it or inject the generic type

```csharp
MyConstructor(BusClient<AdvancedMessageContext> busClient)
{

}
```

**Comment by jayrulez** [comment]
I pasted the wrong code:
This is what I have but have the same results.

services
				.AddRawRabbit<AdvancedMessageContext>(
                    config => config.SetBasePath(_rootPath)
                        .AddJsonFile("rawrabbit.json"),
					container => { 
                        container.AddSingleton(LoggingFactory.ApplicationLogger);
                    })
				.AddSingleton<IConfigurationEvaluator, AttributeConfigEvaluator>()

**Comment by jayrulez** [comment]
This method is called internally

```
		public static IServiceCollection AddRawRabbit<TMessageContext>(this IServiceCollection collection, Action<IConfigurationBuilder> config = null, Action<IServiceCollection> custom = null) where TMessageContext : IMessageContext
		{
			return vNext.IServiceCollectionExtensions
				.AddRawRabbit(collection, config, custom)
				.AddRawRabbitExtensions<TMessageContext>()
				.AddSingleton<IBusClient>(c =>
				{
					LogManager.CurrentFactory = c.GetService<ILoggerFactory>();
					return new ExtendableBusClient(collection.BuildServiceProvider());
				});
		}
``` 

Which adds a non-generic ExtendableBusClient. Is this intended?

**Comment by jayrulez** [comment]
So it turns out I was using the wrong namespaces. Everything works as expected now except for the lingering background process.
