### ISSUE TITLE
Question: Nack with properties

### ISSUE THREAD

**Issue by jayrulez** [pardahlman/RawRabbit#115]
Is there a way to Nack messages and tell rabbitmq not to requeue them?

Would I need to write an extension to do this?

**Comment by jayrulez** [comment]
I modified RawRabbit to achieve this. I modified the Nack action to accept a nullable bool.

So I can do context.Nack(false);

Are you interested in having this patch in a pull request?

I'm not able to run the test cases on Linux so I'm not sure if this breaks any test cases.

**Comment by pardahlman** [comment]
What are the scenarios where you would want to `Nack`, but don't requeue? Isn't that action similar to just `Ack`:ing?

**Comment by jayrulez** [comment]
We are doing this in the code base we are migrating from. I'm trying not to change too much functional behaviour in order to make the transition smoother. I see where I can just use my own message context and enhancer to do this. 

Do you see any benefits to nacking without requeueing? 

Only thing I can think of really is if we need to check the statistics on nacked messages but we do not wish to requeue those messages because they cannot/should not be processed (anymore).

**Comment by jayrulez** [comment]
If this were to be added, I'd opt for exposing all nack options anyway.

**Comment by pardahlman** [comment]
Sorry for not getting back to you earlier. `Nack` is implemented in the advanced context; it makes sense to add the option for re-queue as an optional argument 👍
