### ISSUE TITLE
Publish/Subscribe not acknowledging message - async issue?

### ISSUE THREAD

**Issue by JeffB1** [pardahlman/RawRabbit#130]
I have a very standard pub/sub taken from the sample. 

```
          this.mqClient = BusClientFactory.CreateDefault();
            this.mqClient.SubscribeAsync<EmailConfirmationRequest>(async (msg, context) =>
            {
                await ProcessEmailConfirmationRequest(msg);
            });
```

When I publish a message, the subscribe fires and it successfully process the email as required. However, if I stop and restart the app, the message is still in the queue and it fires the subscribe again. It just doesn't clear.

I suspect it has something to do with the await because if I just do a Console.WriteLine it works as expected.

**Comment by pardahlman** [comment]
@JeffB1 there are [plenty integration tests](https://github.com/pardahlman/RawRabbit/blob/stable/test/RawRabbit.IntegrationTests/SimpleUse/PublishAndSubscribeTests.cs) where we do async/await within a message handler, so I don't think that is the problem.

I suspect that the issue is `ProcessEmailConfirmationRequest`. Could it be that it locks the thread so that RawRabbit never gets the chance to `Ack` the message?

To trouble shoot, I suggest that you:

1. After consuming a `EmailConfirmationRequest` look in the Management Plugin to verify that the message is not present as `Unacked`. If that is the case, then the message will be requeued if you kill the process
2. Change the  call to `ProcessEmailConfirmationRequest` to `await Task.Delay(TimeSpan.FromSeconds(2))` to verify that the problem is not with async/await.

**Comment by JeffB1** [comment]
@pardahlman  Ok. Option 2 shows that the message can be deleted. so that means its got to be some code in my ProcessEmailConfirmationRequest method. Inside that method I call:

```
using (var client = BusClientFactory.CreateDefault())
{
      await client.PublishAsync(emailRequest);
}
```

When I remove that bit of code, it goes back to working ok, so that seems like the problem.
Basically I want to process the message by translating it to new content and stick back on a queue. Am I taking the wrong approach?

**Comment by pardahlman** [comment]
Creating a new `BusClient` from the `BusClientFactory` is a pretty expensive operation, that includes creating a new connection to the broker together with a few channels. Typically you want one connection per application.

Is there a reason why you don't use the existing BusClient to publish the message

```csharp
var client  = BusClientFactory.CreateDefault();
client.SubscribeAsync<EmailConfirmationRequest>(async (msg, context) =>
{
	// do things with content
	await client.PublishAsync(emailRequest);
});

Looking at your code I see another potential issue. If you consume a message and the re-publish it, it will be added to the queue again and then consumed again of the same handler, that will later re-add it again.. Could you problem be that you have an eternal loop?

**Comment by JeffB1** [comment]
@pardahlman  No reason. I've only just started using RabbitMQ and RawRabbit so not sure of what best practices are. The business client is being used in an ASP.NET Core app. Should I add a singleton service to the app and inject that to the various places where I want to handle queueing?

It's two different messages and two different queues that I am using. The idea is to move from one queue to the next with each subscriber taking some action. At least I think that is what is happening. My understanding is that they are two different class types so should be handled in two separate queues. And that seems to work ok. If I was republishing to the same queue, I would expect an endless loop of messages and I am not seeing that. The issue is simply that the message is not being marked as processed so when the app restarts, it subscribes and gets the same message again.

**Comment by pardahlman** [comment]
If you are in a .NET Core context, I suggest creating an instance with the [extension method on `ServiceCollection`](http://rawrabbit.readthedocs.io/en/master/Getting-started.html#vnext-application-wire-up).

You could also look at the [sample code for ASP.NET Core App](https://github.com/pardahlman/RawRabbit/tree/stable/sample/RawRabbit.AspNet.Sample) that is available in the repo.

Hope this helps!

**Comment by JeffB1** [comment]
I will give that a go. The process itself is not doing much. It prepares an object in a certain way depending on what was passed in and the it simply queues another message using RawRabbit. That message is handled in a different bit of code. That code is a bit more complicated as its emailing the text generated from the first queue.

**Comment by JeffB1** [comment]
Now that I am following pattern as per sample app it appears to be working ok.
