### ISSUE TITLE
Running behind load balancer

### ISSUE THREAD

**Issue by jayrulez** [pardahlman/RawRabbit#148]
I've set up a bunch of publishers and consumers in an app I'm working on.

Running one instance, everything is okay.

However, for the majority of the messages published, I only want one subscriber to handle it.

Currently, the same subscriber for all running instances of the application will handle the message.

How can I prevent this allowing only one consumer from only 1 instance of the application to handle the message?

@pardahlman

**Comment by pardahlman** [comment]
@jayrulez - good question! Is your scenario that you have multiple instances of your application, but you only want one of the instances to subscribe to the messages? If so, the simplest way would be to do a check before calling the subscribe method

```csharp
if(ShouldSubscsribe())
{
    _busClient.SubscribeAsync<Message>();
}
```
Where `ShouldSubscribe` evaluates based on things like server name or  `web.config`.

**Comment by jayrulez** [comment]
@pardahlman  Yes I have multiple instances of the application, but I only want one of the instances to consume the message. I still want all instances of the application to subscribe to the messages. 

Much like a round robin work queue.
Like what's happening here I think: https://www.rabbitmq.com/tutorials/tutorial-two-dotnet.html

It works like I want it to in the plugin(PHP project) we are migrating from.  They use a direct exchange type and  the default nameless exchange.

I tried to use a direct exchange with rawrabbit. The message gets published but the subscriber code never gets invoked.

Am i doing something wrong here?

`
            _busClient.SubscribeAsync<NewChatMessage>(async (message, context) =>
            {
                _logger.LogInformation($"Received message: {JsonConvert.SerializeObject(message)}");

//code here
            }, options =>
            {
                options.WithQueue(queueOptions =>
                {
                    queueOptions.WithName($"chat_connection_{Guid.NewGuid()}");
                    queueOptions.WithAutoDelete(true);
                    queueOptions.WithDurability(false);
                });

                options.WithExchange(exchangeOptions => {
                    exchangeOptions.WithType(ExchangeType.Direct);
                    exchangeOptions.WithName("chat");
                });

                options.WithNoAck(false);
            });
` 

publisher code:

`
                                    await busClient.PublishAsync<NewChatMessage>(newChatMessage, configuration: options =>
                                    {
                                        options.WithExchange(exchangeOptions => {
                                            exchangeOptions.WithType(ExchangeType.Direct);
                                            exchangeOptions.WithName("chat");
                                        });
                                    });
`

**Comment by jayrulez** [comment]
It seems this is only possible if the routing key is the same as the name of the queue.

However,  I don't seem to have full control over the routing key as .# is appended automatically.

Is there a way I can override this?

**Comment by jayrulez** [comment]
It turns out that it already works as expected:
http://rawrabbit.readthedocs.io/en/master/Multiple-Subscribers-for-Messages.html

I only reliazed a different behaviour because I generated an unpredictable queue name.
