### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by senj** [pardahlman/RawRabbit#149]
Hello, does RawRabbit support Clusters?
Functionality like automatic reconnection if one node goes down?

**Comment by pardahlman** [comment]
Well, yes. `RawRabbit` relies on the underlying `RabbitMQ.Client` and its functions to automatic reconnect, recover topology etc. You can [read more about that in the documentation](http://rawrabbit.readthedocs.io/en/master/configuration.html#recovery-from-network-failures).

However, a client to the message broker does not have the ability to resolve a partition or Mnesia. This is entirely up to the brokers and the cluster configuration. There are lots of information on [RabbitMq's](https://www.rabbitmq.com/partitions.html) site.

Hope this helps!
