### ISSUE TITLE
CQRS Extension Suggestion

### ISSUE THREAD

**Issue by cemremengu** [pardahlman/RawRabbit#155]
So here is what I suggest as an extension for the upcoming 2.0:

These ideas are mainly based on what I have learned from [this example](https://github.com/cemremengu/ristorante)

We separate commands (pub/sub) and queries (request/response) with different interfaces.

```
public interface IHandle<in T>
{
	Task Handle(T message); // subscribe
}

public interface IRequest<in TRequest, TResponse>
{
	Task<TResponse> Handle(TRequest request); // respond
}
```

which will allow us to define services like

```
public interface IBucketService : 
	IRequest<BucketMessages.FindBucketById, Bucket>,
	IHandle<ImportBatchFromBytes>
{
      // bunch of Handle methods
}
```

Then we can do something like `bus.Register(BucketService)` then `bus.Publish(ImportBatchFromBytes)`

We can also define a process manager in the same way to handle and coordinate events:

```
public interface IMyProcessManager: 
	IHandle<BucketCreated>,
	IHandle<BatchImported>
{
      // bunch of Handle methods
}
```

A different approach is to have each handler in a different class:

```
public class FindBucketByIdHandler: IRequest<BucketMessages.FindBucketById, Bucket>
{
      public Task<Bucket> Handle(BucketMessages.FindBucketById request)
      {
         //  ... do stuff
      }
}
```

then do `bus.RespondAsync<BucketMessages.FindBucketById, Bucket>(FindBucketByIdHandler);`

or simply `bus.Register(FindBucketByIdHandler)`

**Comment by pardahlman** [comment]
@cemremengu - thanks a bunch for this 👍. I agree in part with your suggestion. However, I have some follow-up comments and opinions that I'd like to hear your thought on.

One problem I see is that there is no way to configure queue/exchange/routingkey and other topology features using this pattern. It could be important if someone for some reason wants to use, say a certain prefeetch count or change devliery mode of the message.

I think that it is a pretty common scenario that you want to use DI in you `IMyProcessManager`. If `RawRabbit` registers the process manager by type (I'm assuming now that you mean `bus.Register(typeof(FindBucketByIdHandler))`), it needs to know how to resolve constructor arguments, which means that the client needs to have the application container. Or am I getting you wrong?

When I'm building large services I tend to create interfaces that are implementation agnostic, so I would create an `IBucketManager` (uh-oh! not manager) that injected the `IBusClient` and registered message handlers etc. That way, I could mock it etc. With the `IHandler`/`IRequester` pattern, the implementation (RabbitMq/RawRabbit) is tightly coupled in the interface. Thought?

**Comment by pardahlman** [comment]
New year, new lines of code to write! Have you given any more thoughts to this, @cemremengu?

**Comment by jayrulez** [comment]
This seems similar to what we have implemented.

We allow passing Action<ISubscriptionConfigurationBuilder>to configure it.

**Comment by moconnell** [comment]
One comment on this: the purpose of CQRS is actually to separate your reads from your writes.

It's confusing things some to suggest that this always maps 1:1 with pub/sub vs. RPC. Perhaps in an ideal world it should, but that's another debate :)

**Comment by pardahlman** [comment]
Hello @moconnell - thanks for your input! Not 100% sure I follow your argumentation, could you elaborate some more?

I'm open to a discussion here, I think that together we will find a clean API for this. Actually this ticket could be a great introduction to writing `Opertations` for 2.0.

**Comment by cemremengu** [comment]
CQRS maybe the wrong word here, now I see that what I suggested is more of like the [MediatR](https://github.com/jbogard/MediatR) but with a twist of RabbitMQ

But queues may have different configurations so I am not sure how to tackle having different configs.

**Comment by moconnell** [comment]
To elaborate, with CQRS, you typically have one service that handles read-only queries - and another that accepts commands that change the data. 

So I can see how this could map to a system where you have pub/sub for the reads and RPC for updates. 

But the reality is that many (most?) are still stuck in a fairly procedural mindset and consequently use RPC for almost everything.

**Comment by pardahlman** [comment]
I'm cleaning up the issues, and closing this for now. Feel free to re-open or create a new issue should the need arise 😄
