### ISSUE TITLE
Consumer concurrancy throttle

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/RawRabbit#169]
Based on [community feedback](https://github.com/pardahlman/RawRabbit/issues/168#issuecomment-270205551) as well as [previous request](https://github.com/pardahlman/RawRabbit/issues/144#issuecomment-260069252) `RawRabbit` should support some sort of throttle mechanism for consumers.

**Comment by pardahlman** [comment]
Concurrency is managed by provided _consume semaphore_ (if any) in the `IPipeContext`. The semaphore is declared by the client, opening up for the users to define logic as to which semaphore to provide/reuse. For example, if the same semaphore is provided across the application, the throttle will be "global". If the semaphore only allows `1` concurrent thread to enter, the consume will be sequential.

If no semaphore is provided, there will be no consume throttle (similar to 1.x).

The `IPipeContext` can be manipulated by the optional action in the subscribe method.

```csharp
await subscriber.SubscribeAsync<BasicMessage>(async message =>
{
	// do stuff
}, context: c => c.Properties.TryAdd(PipeKey.ConsumeSemaphore, new SemaphoreSlim(3));
```
The expression can be simplified by using convenience method (extension)

```csharp
await subscriber.SubscribeAsync<BasicMessage>(async message =>
{
	// do stuff
}, context: c => c.AddConsumeSemaphore(concurrency: 3));
```

**Comment by cocowalla** [comment]
Just wanted to say I think this is quite a clever and uncomplicated solution!
