### ISSUE TITLE
add routing slip features

### ISSUE THREAD

**Issue by yonglehou** [pardahlman/RawRabbit#188]
does rawrabbit add routing slip features like MassTransit Courier？

**Comment by pardahlman** [comment]
Hello!
I haven't used the routing slip feature of MassTransit myself, but I think that the [Message Sequence feature](http://rawrabbit.readthedocs.io/en/master/message-sequence.html) does something similar.

```csharp
var sequence = _client.ExecuteSequence(c => c
    .PublishAsync<UserLoginAttempted>()
    .When<GeograficPositionDetected>((msg, ctx) => ActOnGeograficPosition(msg.Position))
    .When<ContactDetailsLoaded>((msg, ctx) => ActOnContactDetails(msg.Details))
    .Complete<UserLoggoedIn>()
);
```
In the coming 2.0 release (available as pre release now) you could also use the [State Machine operation](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/StateMachine/Generic/ProcessTriggers.cs) for long lived executions.

Hope this helps!

**Comment by yonglehou** [comment]
thanks for your reply，i get it.
