### ISSUE TITLE
Can't Seem to Make ExecuteSequence Work

### ISSUE THREAD

**Issue by jbarket** [pardahlman/RawRabbit#196]
Using 2.0.0-beta3 with pretty much every optional package installed.

I have a console app and a web app like the example. I'm trying to set up a sequence so that when I publish, I can return an error if there is one. Controller code snippet:

```
var itRan = false;
var sequence =
    this.busClient.ExecuteSequence(s => s
        .PublishAsync(new ItemRequest { Id = id })
        .When<NotFoundResult, MessageContext>(
            (failed, ctx) =>
            {
                itRan = true;
                this.Response.StatusCode = (int)HttpStatusCode.NotFound;
                return Task.FromResult(true);
            }, it => it.AbortsExecution())
        .Complete<ItemResponse>());

await sequence.Task;

if (itRan)
{
    Log.Debug("It ran");
}
```

The console app snippet:

```
var item = db.Items.FirstOrDefault(i => i.Id == request.Id);

if (item == null)
{
    await this.busClient.PublishAsync(new NotFoundResponse());
}

await this.busClient.PublishAsync(this.mapper.Map<ItemResponse>(item));
```

If I request an item that exists, it works as expected. However, if I request one that doesn't exist, it doesn't change the value of `itRan` or the StatusCode. Setting debug points inside of my When, it never seems to trigger. I see the event get emitted in the log:

[16:43:59] [$24] [INFO] [BasicPublishMiddleware]: Performing basic publish with routing key notfoundresponse.0d9e3deb-da91-499c-ad0e-e0e51a889e18 on exchange shared.data.messages.

But still no change.

Any ideas what I'm doing wrong?

**Comment by pardahlman** [comment]
All in on the enricher packages? I like it! 👍 

I think your code looks good. My first thought was that the console app lacked some enricher packages (it need `GlobalExecutionId` for the sequences to work correctly). However, I can see from the log file that you enclosed that you publish routing key containing the execution id.

There are a few things you can look for. If you have the management plugin enabled, you could open the view for the queue that should be named something like  `notfoundresponse_0d9e3deb-da91-499c-ad0e-e0e51a889e18` (or whatever the id is for the sequence). Do you see that a message is received?

You could, just to verify that the message is delivered, add a subscriber somewhere that subscribes to the same message

```csharp
busClient.SubscribeAsync<NotFoundResult>(notFound => {
    // break point, or log to see that you get the message
})
```
There should be log files from the client performing the sequence.  One of the first things you should see is _Invoking consumer pipe for message {msgId}_, and then some header deserialisation. Can you find these logs and post them? While you're at it, can you add the code snippets on how you wire up the bus client in both applications?

Thanks!

**Comment by pardahlman** [comment]
Closing this now. Feel free to re-open :)
