### ISSUE TITLE
Will you add the persistence with databse of the message sequence and state machine to the rawrabbit  in v2.0 version?

### ISSUE THREAD

**Issue by yonglehou** [pardahlman/RawRabbit#197]

**Comment by pardahlman** [comment]
Hello, @yonglehou - thanks for your question!

The persistence mechanism will not be incorporated in the framework. There are, however, delegates available when registering the state machine that you can use to wire up custom persistance. Here's an code example 

```csharp
new RawRabbitOptions
{
	Plugins = p => p.UseStateMachine(
		id => _sqlRepo.GetAsync(id),
		model => _sqlRepo.AddOrUpdateAsync(model)
	)
};
```

Hope this helps!

**Comment by yonglehou** [comment]
thanks for your reply，i get it.
