### ISSUE TITLE
Need idea on underlying data structures for implementing Message Sequence extension

### ISSUE THREAD

**Issue by anupavanm** [pardahlman/RawRabbit#203]
We would like to implement Message Sequence extension,
Wondering how the data structures look like :
Ex: for using the implementation provided in 
 "Should_Call_Message_Handler_In_Correct_Order()" Test.

**Comment by pardahlman** [comment]
Hello @anupavanm!

If you are running version 1.x you would need to download the [`RawRabbit.Extensions`](https://www.nuget.org/packages/RawRabbit.Extensions/) package and create an instance of the `ExtendableBusClient` (usually done through the [`RawRabbitFactory`](https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit.Extensions/Client/RawRabbitFactory.cs)). There are more information about extensions in the [documentation](http://rawrabbit.readthedocs.io/en/master/Extending-RawRabbit.html)

If you ware running version 2.x you just need to reference the package [`RawRabbit.Operations.MessageSequence`](https://www.nuget.org/packages/RawRabbit.Operations.MessageSequence/) and register the "plugins" for GlobalMessageId and StateMachine (like I'm doing [here](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/MessageSequence/MessageSequenceTests.cs#L26-L28)).

Not 100% sure this answers your question. Feel free to elaborate what your looking for or any particular problem you've run into.

**Comment by pardahlman** [comment]
Hello again, closing this for now. If my answer didn't make sense, feel free to re-open.
