### ISSUE TITLE
BasicConsumeAsync throws when FromQueue("QueueName") is not specified

### ISSUE THREAD

**Issue by cemremengu** [pardahlman/RawRabbit#206]
This works:

```
await _busFactory.Create().BasicConsumeAsync(async args =>
{
//code here
},
ctx => ctx.UseConsumerConfiguration(
	cfg => cfg.Consume(c => c
			.FromQueue("MyQueueName")
			.WithPrefetchCount(350)
			.WithRoutingKey("gsm.cell.kpi"))
		.OnDeclaredExchange(e => e
			.WithName("abid.kpi")
			.WithType(ExchangeType.Topic))));
```

But if the `.FromQueue("MyQueueName")` is omitted it will throw a cryptic exception `String reference not set to an instance of a String. Parameter name: s`

This is probably caused by https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit/Consumer/ConsumerFactory.cs#L54-L62

when a mandatory config is not specified

**Comment by pardahlman** [comment]
The question, though, is - if you don't say from which queue to consume from, how will we know which queue to consume from :)

**Comment by pardahlman** [comment]
I agree with you, though, that RawRabbit could do an argument check and throw a nice error instead of relying on the underlying `RabbitMQ.Client` exception.
