### ISSUE TITLE
WithPrefetchCount is not honored ?

### ISSUE THREAD

**Issue by cemremengu** [pardahlman/RawRabbit#207]
I specify the configuration:

```
                ctx => ctx.UseConsumerConfiguration(
                    cfg => cfg.Consume(c => c
                            .FromQueue("gsmcellkpireceived")
                            .WithPrefetchCount(350)
                            .WithRoutingKey("gsm.cell.kpi"))
                        .OnDeclaredExchange(e => e
                            .WithName("abid.kpi")
                            .WithType(ExchangeType.Topic))));
```
But the prefetch looks zero ?

![queue](https://cloud.githubusercontent.com/assets/1297759/24189658/eb75cc3e-0ef6-11e7-8446-c8d2c8fc9e83.PNG)

**Comment by pardahlman** [comment]
Thanks for reporting this! I'll look into this, if unless you want to dig into the code?

**Comment by cemremengu** [comment]
Searching a bit, I think 

https://github.com/pardahlman/RawRabbit/blob/3bc63b1972537092bf2d5378b69c904ba22af86d/src/RawRabbit/Consumer/Eventing/EventingBasicConsumerFactory.cs#L63 

may be the problem after seeing this [discussion](https://github.com/php-amqplib/php-amqplib/issues/297) 

looks like prefetch size must be `null` ? Any ideas ?

**Comment by pardahlman** [comment]
Hello @cemremengu - I looked into this a bit further, and it turns out that the code you are referring got lost somewhere on the way to 2.0. It was such a small fix once I found the reason, so I did it myself. Hope you haven't invested to much time at your end!

**Comment by cemremengu** [comment]
I tried to locate the code setting the `prefetchCount` for sometime but couldn't find and gave up. So that explains everything :smile: 

Thanks for the quick fix!

**Comment by pardahlman** [comment]
No worries, mate!
