### ISSUE TITLE
Broadcast model

### ISSUE THREAD

**Issue by PeterKottas** [pardahlman/RawRabbit#213]
Hey mate, again one from the series of my annoying questions :p I am using publish/subscribe model which, if I understand it correctly if you have 1 publisher and N subscribers, only one of them will get the message. Do you have something like broadcast model when all N would get the update? Or is it something I could do with config? Thanks

**Comment by pardahlman** [comment]
Heya! Not annoying at all. Yes, it works, you can read about it here: http://rawrabbit.readthedocs.io/en/master/Multiple-Subscribers-for-Messages.html

**Comment by PeterKottas** [comment]
Perfect, I though it will be simple. Looks good, I'll give it a shot and let you know if I have any problems. Thanks!

**Comment by PeterKottas** [comment]
No problems indeed. Works like a charm as usual (after some persuasion :D )
