### ISSUE TITLE
Structuremap

### ISSUE THREAD

**Issue by shibukraj** [pardahlman/RawRabbit#214]
Hello all,

I am trying to implement the dependency injection using Structremap similar to Autofac and Ninject. This is required because the project I am planning to use the RawRabbit uses Structuremap. Once we are done with and tested will send a PR request.

For developing we are just using Ninject as the baseline. But I am facing one issue as well. So if we have any experts in structremap using Rawrabbit - any help/direction is highly appreciated.

In NInject for IMessageSerializer, the registration is done as follows.

	Kernel.Bind<IMessageSerializer>()
	.To<JsonMessageSerializer>()
	.InSingletonScope()
	.WithConstructorArgument("config", (Action<JsonSerializer>)null);

We followed the same pattern for Structuremap but seems like that is not working.

For<IMessageSerializer>()
                    .Use<JsonMessageSerializer>()
                    .Ctor<Action<JsonMessageSerializer>>()
                    .Is("config", c => c.GetInstance<Action<JsonMessageSerializer>>())
                    .Singleton();

When we try to run we get the following exception.
Unable to create a build plan for concrete type Action<JsonSerializer>

new Action<JsonSerializer>(Object, IntPtr method)
 ┗ Object = **Default**
        IntPtr method = Required primitive dependency is not explicitly defined

1.) Attempting to create a BuildPlan for Instance of Action<JsonSerializer> -- Action<JsonSerializer>
2.) new JsonMessageSerializer(*Default of JsonSerializer*, *Default of Action<JsonSerializer>*)
3.) RawRabbit.Serialization.JsonMessageSerializer
4.) Instance of RawRabbit.Serialization.IMessageSerializer (RawRabbit.Serialization.JsonMessageSerializer)

While running diagnostics in Structuremap with WhatDoIScan() and WhatDoIHave() it seems like all the registrations are there but the named /constructor injection is not working as expected.

Any help is highly appreciated

Thanks

**Comment by pardahlman** [comment]
Hello, @shibukraj 👋 

Thanks for your willingness to help out! I haven't used Structremap a lot, so I might not be able to give you specific help. Looking at the code you've provided (`.Use().Ctor<Action>()`) it looks like you try to use a constructor with only an `Action` argument. Could the problem be that:

1. The [constructor has two arguments](https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit/Serialization/JsonMessageSerializer.cs#L14), `JsonSerializer` and `Action<JsonSerializer>`
2. You specify a constructor with an untyped `Action`, the constructor actually requires an `Action<JsonSerializer>`

I might be wrong though!

**Comment by pardahlman** [comment]
Hello again @shibukraj - I haven't heard back from you, so... closing this for now. Feel free to open new issue if you have RawRabbit specific problems in your efforts with Structuremap 👍
