### ISSUE TITLE
Set queue name with or without INamingConvention

### ISSUE THREAD

**Issue by alpeshv** [pardahlman/RawRabbit#217]
@pardahlman what is the easiest way to set queue name? I could not find an example anywhere on how to do it. If INamingConvention is the only way then how to do it with INamingConvention? 

I have tried specifying queue name following way but it still uses _appname as postfix.

```
client.SubscribeAsync<string>(async (msg, context) =>
            {
              Console.WriteLine("Recieved: {0}", msg);
            }, cfg=>cfg.WithQueue(q=>q.WithName("ha.test")));
```

Thanks in advance

**Comment by pardahlman** [comment]
Hello @alpeshv - thanks for reporting this!

It is a bit problematic that the app name is appended without the end user having control over it. Know that these things have changed in 2.0, so things will be easier in the feature :)

As for your question, perhaps this can guide you in the right direction: https://github.com/pardahlman/RawRabbit/issues/210#issuecomment-291149809

**Comment by pardahlman** [comment]
I'm interpreting your thumbs up that it solved your problem. Closing this now. Feel free to open again if this is still a problem

**Comment by alpeshv** [comment]
@pardahlman It got fixed by this.

http://stackoverflow.com/questions/43521608/rawrabbit-set-queue-name-with-or-without-inamingconvention[http://stackoverflow.com/questions/43521608/rawrabbit-set-queue-name-with-or-without-inamingconvention](url)

**Comment by shahabganji** [comment]
How is it possible to set the queue name for publish scenario? 

```cs
 this.Client.PublishAsync(data,
                ctx => ctx.UsePublishConfiguration(cfg => {
                })
            );
```
