### ISSUE TITLE
Consumer not able to reconnect to cluster

### ISSUE THREAD

**Issue by alpeshv** [pardahlman/RawRabbit#220]
If I put publish and subscribe in the same method, and if master node from cluster goes down, it doesn't crash. If I put publish and subscribe in the different app, consumer gets crashed when master node goes down.

Works:
```
private static void SendReceiveRaw()
        {
            var config = new RawRabbitConfiguration
            {
                Username = "test",
                Password = "test",
                Port = 5672,
                VirtualHost = "/",
                Hostnames = { "host1", "host2" },
                Queue =
                {
                    AutoDelete = false,
                    Durable = true,
                    Exclusive = false
                },
                RouteWithGlobalId = false,
                AutomaticRecovery = true
            };

            var client = BusClientFactory.CreateDefault(config);

            client.SubscribeAsync<string>(async (msg, context) =>
            {
                Console.WriteLine("Recieved: {0}", msg);
            }, cfg => cfg.WithQueue(q => q.WithName("ha.test.dev")).WithSubscriberId(""));

            for (var i = 1; i < 500; i++)
            {
                client.PublishAsync(string.Format("MESSAGE {0}", i), configuration: cfg => cfg.WithExchange(ec => ec.WithName("dev.direct").WithType(ExchangeType.Direct)).WithRoutingKey("dev-av"));
                Console.WriteLine("Message published {0}", i);
                Thread.Sleep(2000);
            }
        }
```

Doesn't Work:
App1
```
private static void SendRaw()
        {
            var config = new RawRabbitConfiguration
            {
                Username = "test",
                Password = "test",
                Port = 5672,
                VirtualHost = "/",
                Hostnames = { "host1", "host2" },
                Queue =
                {
                    AutoDelete = false,
                    Durable = true,
                    Exclusive = false
                },
                RouteWithGlobalId = false,
                AutomaticRecovery = true
            };

            var client = BusClientFactory.CreateDefault(config);

            for (var i = 1; i < 500; i++)
            {
                client.PublishAsync(string.Format("MESSAGE {0}", i), configuration: cfg => cfg.WithExchange(ec => ec.WithName("dev.direct").WithType(ExchangeType.Direct)).WithRoutingKey("dev-av"));
                Console.WriteLine("Message published {0}", i);
                Thread.Sleep(2000);
            }
        }
```

App2
```
private static void ReceiveRaw()
        {
            var config = new RawRabbitConfiguration
            {
                Username = "test",
                Password = "test",
                Port = 5672,
                VirtualHost = "/",
                Hostnames = { "host1", "host2" },
                Queue =
                {
                    AutoDelete = false,
                    Durable = true,
                    Exclusive = false
                },
                RouteWithGlobalId = false,
                AutomaticRecovery = true
            };

            var client = BusClientFactory.CreateDefault(config);

            client.SubscribeAsync<string>(async (msg, context) =>
            {
                try
                {
                    Console.WriteLine("Recieved: {0}", msg);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Error: {0}", ex.Message);
                    Console.ReadKey();
                }
            }, cfg => cfg.WithQueue(q => q.WithName("ha.test.dev")).WithSubscriberId(""));
        }
```

I had tried sharing same client instance across both the app but it still doesn't work.

**Comment by pardahlman** [comment]
Hi @alpeshv - thanks for reporting this!

It looks like you are running the 1.x branch of the client. Are you running 1.10.3? I'm wondering because a similar issue was fixed in #143.

Also, I want to make sure that I understand the issue correctly. When you say "consumer gets crashed" do you mean that the consumer crashes but app still runs, or that the app itself crashes?

It would also help if there are any stack traces that can give me a clue to what the exception might be. The perhaps easiest way would be to use a file logger on the app that crashes an paste the log entries here that is related to the crash.

**Comment by alpeshv** [comment]
@pardahlman thanks for replying back quickly. 

I have just two simple console apps, one acting as publisher and other as consumer. So the consumer app gets crashed when I stop main cluster node. Publisher manages to recover but not consumer. Yes I am using 1.10.3.

As you can see I am trying to catch exception everywhere but it doesn't break anywhere and just crashes. Can you spot any obvious issue with the way I am handling exception?

```
static void Main(string[] args)
        {
            Console.WriteLine("Message handler...");

            try
            {
                ReceiveRaw();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: {0}", ex.Message);
                Console.ReadKey();
            }

            Console.WriteLine("Message handler started...");
        }

        private static void ReceiveRaw()
        {
            var config = new RawRabbitConfiguration
            {
                Username = "test",
                Password = "test",
                Port = 5672,
                VirtualHost = "/",
                Hostnames = { "host1", "host2" },
                Queue =
                {
                    AutoDelete = false,
                    Durable = true,
                    Exclusive = false
                },
                RouteWithGlobalId = false,
                AutomaticRecovery = true
            };

            try
            {
                var client = BusClientFactory.CreateDefault(config);

                client.SubscribeAsync<string>(async (msg, context) =>
                {
                    try
                    {
                        Console.WriteLine("Recieved: {0}", msg);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("Error: {0}", ex.Message);
                        Console.ReadKey();
                    }
                }, cfg => cfg.WithQueue(q => q.WithName("ha.test.dev")).WithSubscriberId(""));
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: {0}", ex.Message);
                Console.ReadKey();
            }
        }
```

**Comment by pardahlman** [comment]
Hello again!

The try/catch in the `Main` method doesn't really do anything, as the code will execute and return once the consumer is registered. When a message is received, an event is fired that will end up in the message handler you registered. You can probably get some insight by [registering a logger](http://rawrabbit.readthedocs.io/en/master/logging.html) and thus get hold of the internal logs of RawRabbit. Optionally, you could register an delegate the the `UnhandledException` event

```csharp
AppDomain.CurrentDomain.UnhandledException += (sender, args) =>
{
	Console.WriteLine(args.ExceptionObject);
	Console.ReadKey();
};
```
I'll be interested in hearing what you'll find!

**Comment by alpeshv** [comment]
It crashes even after registering `UnhandleledException` delegate. Looks like the issue must be inside an `async ` method and so it is not getting propagated to the main caller. Unfortunately I cannot install VS2015 on my machine and so cannot open xproj to investigate it myself.

**Comment by pardahlman** [comment]
That sounds strange, as that what the `UnhandledException` is meant for. According to its [documentation](https://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception(v=vs.110).aspx) 

> This event provides notification of uncaught exceptions. It allows the application to log information about the exception before the system default handler reports the exception to the user and terminates the application.

Have you tried to wire up a logger?

(Ps. you should be able to fairly easy migrate the project to csproj using [`dotnet migrate`](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-migrate) - that's what I did in the 2.0 branch 👍  )

**Comment by alpeshv** [comment]
`GetDefaultBusClient` is not there. I can't even find it in the code anywhere. So can't use 

```
RawRabbitFactory.GetDefaultBusClient(
            ioc => ioc.AddSingleton<ILoggerFactory, RawRabbit.Logging.Serilog.LoggerFactory>()
);
```

**Comment by pardahlman** [comment]
Some of the extension methods exist in different nuget packages that you perhaps haven't installed. Looking at your original code, it looks like you are using the `BusClientFactory` so perhaps [this method])https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit.vNext/BusClientFactory.cs#L26) may work for you?

**Comment by alpeshv** [comment]
I tried to use https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit.vNext/BusClientFactory.cs#L32 since I had to pass my own config as well but I wasn't sure how to pass config through first param.

**Comment by alpeshv** [comment]
Hi @pardahlman ,

Thanks for your time. I will investigate this issue myself over the weekend and will let you know what my findings are.

**Comment by alpeshv** [comment]
I think the issue is in `RabbitMQ.Client` library. I have tried handling connection failure myself and got the same issue. Delegate method for `consumer.Received` fails when connection node gets down and it doesn't propagate error to the caller. I had tried different ways to catch the error but it always crashes.

**Comment by alpeshv** [comment]
Sorry my bad. I was expecting an exception when my node goes down but RabbitMQ client waits for connection to come back and so I doesn't throw any error. But I also needed to keep my console app alive by adding `Console.ReadKey()` as the last statement inside `main()` which was missing.

**Comment by pardahlman** [comment]
Alright, thanks for getting back! Not 100% I follow, is this still a problem or have you solved it? :)

**Comment by alpeshv** [comment]
No issue any more.  You can close this issue. Thanks.

**Comment by pardahlman** [comment]
Superb! Good luck 😉
