### ISSUE TITLE
Trouble with NLog and Ninject

### ISSUE THREAD

**Issue by msnelling** [pardahlman/RawRabbit#244]
Hi,
We're using NLog and Ninject for our project but I'm having an issue getting the logging to work. I'm initialising RawRabbit and replacing the default LoggerFactory with the below code but nothing from RawRabbit isgetting to NLog.
```
            // Configure RawRabbit with connection string
            var connectionString = ConfigurationManager.ConnectionStrings["RabbitMQ"];
            var config = ConnectionStringParser.Parse(connectionString.ConnectionString);
            Kernel.RegisterRawRabbit(config);

            // NLog logging
            Kernel
                .Rebind<ILoggerFactory>()
                .To<RawRabbit.Logging.NLog.LoggerFactory>()
                .InSingletonScope();
```

**Comment by pardahlman** [comment]
Hi @msnelling - thanks for reporting this!

It looks like you are registering the logger factory as intended. Unfortunately, I'm not an expert in Ninject so there might be something that I'm missing. For trouble shooting, you could register the logger factory [with a custom `createFunc`](https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit.Logging.NLog/LoggerFactory.cs#L13) and set a breakpoint in that function to verify that it returns a configured NLog logger.

Let me know if this helps!

**Comment by pardahlman** [comment]
Heads up! In the upcoming release of 2.0 (starting with beta8) the logging implementation is replaced with LibLog, which should mitigate all problems with registering correct logger etc! See #245.

**Comment by msnelling** [comment]
Thanks, any idea when you expect to release 2.0?

**Comment by pardahlman** [comment]
Hopefully soon. All new features are put off to version 2.1 in order to keep the scope for 2.0 fixed. No dates yet, though.

**Comment by pardahlman** [comment]
The majority of my efforts are put into the 2.0 version of the client. If you find something when you trouble shoot the code, I'm more than willing to accept a PR - but I will not spend time on this in the foreseeable future. My suggestion is, if at all possible, to migrate to 2.0 where bugs and issues are addressed as fast as possible 😄

**Comment by pardahlman** [comment]
Logging in 2.x is seamless with whatever logging framework you are using. If at all possible, upgrade to the latest version 👍
