### ISSUE TITLE
Multiple IContextEnhancer

### ISSUE THREAD

**Issue by cortex93** [pardahlman/RawRabbit#248]
Hi,

It would be nice to be able to register multiple IContextEnhancer. I don't want to inherit from ContextEnhancer and still want to have the opportunity to enrich the MessageContext.

**Comment by pardahlman** [comment]
Hi @cortex93 - thanks for reporting this 👍 

I'm not 100% sure I follow. You are free to register your own `IContextEnhancer`. If you want to split up the enhancer into multiple sub-classes, you can register a `MultiplexingContextEnhancer` or something similar that call underlying enhancers. Makes sense?

**Comment by cortex93** [comment]
Yes, make sense but as the default implementation bring some major functionality, it could be a great addition to include it directly in RawRabbit.

**Comment by pardahlman** [comment]
Do you have any specific scenario in mind for this? I believe that in many cases there is a one-to-one mapping between message context type and context enhancer.

**Comment by cortex93** [comment]
I see the MessageContext like HttpContext in asp.net core. So, my idea was to attach a ServiceProvider scope to it. Something like the FeatureCollection in asp.net core could be cool. For eg. you may retry the RetryFeature and have access to RetryInfo and RetryLater or the NackFeature, or MessageServicesProviderFeature.
This way, we can have our own MessageContext but still have access to all the Feature set already provided by RawRabbit framework. Don't really know how it could fit in the MessageContext lifecycle.

**Comment by pardahlman** [comment]
Makes sense! However, I'm a bit hesitant to make such large change in 1.x, as I'm currently putting my efforts at the upcoming version (2.0). If you want to move this forward, you could create a PR for it. Not sure when the next version of 1.x will be released, though. Sorry!

**Comment by pardahlman** [comment]
@cortex93 - I'm putting my efforts in completing 2.0. I think that the work-around with a multiplexing context enhancer suffices at the moment. Closing this ticket.

**Comment by cortex93** [comment]
Yes, sorry for not giving news. I moved to 2.0 and still playing around.
