### ISSUE TITLE
Support more parameters to connectionString

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/RawRabbit#25]
Today, the only (optional) parameter supported in `RawRabbit` is `requestTimeout`. The connectionString should should support all the parameters available at the `RawRabbitConfiguration` configuration object.

A few examples of connectionStrings that should be supported

* `guest:guest:localhost:5672/?autoCloseConnection=true`
* `guest:guest:localhost:5672/?autoCloseConnection=true&requestTimeout=10`
* `guest:guest:localhost:5672/?requestTimeout=10&autoCloseConnection=true`

1. The order of the parameters should not matter
2.  Default values should be used for parameters omitted in the connectionString

**Comment by Originalutter** [comment]
I can do this one!
