### ISSUE TITLE
2.o documentation: Add information on the used packages?

### ISSUE THREAD

**Issue by ChristianSauer** [pardahlman/RawRabbit#250]
Hi,
I really like your project. It reduces the amount of pain by orders of magnitude. RabbitMq as it should be ;)

I notices that the new 2.0 contains a lot of sub packages. Finding which ones you need is relativly difficult. So it would be great if the documentation would contain a small snippet on the used package(s) on the current page

**Comment by pardahlman** [comment]
Hi @ChristianSauer - thanks for your kind words. Documentation is one of the things left to do before 2.0 is released, see issue #184. Parts of [the documentation](https://github.com/pardahlman/RawRabbit/tree/2.0/docs) for 2.0 are in a draft version, it might help you getting started.

Hope this helps!

**Comment by pardahlman** [comment]
Closing this one, as it duplicates #184!
