### ISSUE TITLE
Beta 2: MessageSequence: Make used Exchanges / Queues configurable

### ISSUE THREAD

**Issue by ChristianSauer** [pardahlman/RawRabbit#252]
Currently, it seems only to be possible to configure publishing, but it would be great if we could configure the When and Complete Staes too.
I am doing interop with a python app, which cannot use the conventions used by RawRabbit, so RawRabbit could use my naming scheme :)
It's possibly manually,  (Publish / SubscribeAsync) but I like the totally readable Sequence Syntax

**Comment by pardahlman** [comment]
Hello @ChristianSauer - thanks for reaching out! I think that the feature makes sense in the 2.x branch of the client. The `When` messages are [configured with some custom consume logic](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit.Operations.MessageSequence/StateMachine/MessageSequence.cs#L166) that could be extended to include user provided configuration. Feel free to submit a PR for this 😉

**Comment by ChristianSauer** [comment]
Ok, thank you for the poitner. I will see if my wife can spare me this weekend ;)

**Comment by pardahlman** [comment]
Keeping my fingers crossed 😅 . Let me know if you need any more guidance for this!

**Comment by pardahlman** [comment]
Hello @ChristianSauer -closing this for now. Feel free to re-open if you get the time to do the implementation 😉
