### ISSUE TITLE
Beta8: Serialization type

### ISSUE THREAD

**Issue by msnelling** [pardahlman/RawRabbit#255]
Hi,
I'm looking at porting our app to use RawRabbit 2.0. Beta 8 defines the ISerializer interface as
```
  public interface ISerializer
  {
    string ContentType { get; }
    string Serialize(object obj);
    object Deserialize(Type type, string str);
    TType Deserialize<TType>(string str);
  }
```

How will this work if say my messages are to be serialised as binary protocol buffer messages when the `Serialize()`  function returns a `string` instead of `byte[]`?

**Comment by pardahlman** [comment]
Hello @msnelling - thanks for reporting this.

I believe that you are right, the `ISerializer` assumes that you serialize to string based output (like json, xml ...). At a first glance in the code, it shouldn't be that big of an effort to update the signature, but I have to look closer at it before committing to this change.

In the mean while, it shouldn't be that difficult working around this, as the client is can easily be modified. The [bytes of a published message](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit.Operations.Publish/PublishMessageExtension.cs#L36) is extracted from the serialized message (`string`), and it is possible to update/replace that middleware by using the fluent builder in the `Plugin` property of `RawRabbitOptions`.

**Comment by msnelling** [comment]
Thanks.
I'm having trouble with the `Plugin` syntax, are there any examples?

**Comment by pardahlman** [comment]
You can have a look at the `Enrichers` in the 2.0 branch. There is unfortunately no better documentation at this point.

**Comment by pardahlman** [comment]
Hello again. I've updated the `ISerializer` interface so that it works with byte arrays. To verify that it works, I've also created an enricher that changes serializer to protobuf 👉 https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/Enrichers/ProtobufTests.cs

This will be part of beta9.

**Comment by msnelling** [comment]
Thanks!

**Comment by pardahlman** [comment]
Releaed
