### ISSUE TITLE
Question: Multiple message types on same queue

### ISSUE THREAD

**Issue by MrGlenThomas** [pardahlman/RawRabbit#261]
Is it possible to subscribe to multiple message types on the same queue and have RawRabbit direct the message to the relevant subscriber?

```
var subscription1 = _rabbitMqClient.SubscribeAsync<SomethingHappened>(
	async (received, context) => Console.WriteLine("Received SomethingHappened"),
	builder => builder.WithQueue(queue => queue.WithName("MyQueueName"))
	.WithExchange(RabbitConfiguration.MainExchange).WithRoutingKey(SomethingHappenedRoutingKey));

var subscription2 = _rabbitMqClient.SubscribeAsync<SomethingElseHappened>(
	async (received, context) => Console.WriteLine("Received SomethingElseHappened"),
	builder => builder.WithQueue(queue => queue.WithName("MyQueueName"))
	.WithExchange(RabbitConfiguration.MainExchange).WithRoutingKey(SomethingElseHappenedRoutingKey));
```

When I try this with RawRabbit 1.10.3 I get 
`Newtonsoft.Json.JsonSerializationException: Type specified in JSON 'RawRabbit.TestConsole.Messages.SomethingElseHappened, RawRabbit.TestConsole, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with 'RawRabbit.TestConsole.Messages.SomethingHappened, RawRabbit.TestConsole, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'`

I want to receive various message types in order e.g. SomethingCreated, SomethingUpdated, SomethingDeleted. So I am using a single queue to ensure ordering.

**Comment by pardahlman** [comment]
Hello @MrGlenThomas - thanks for reaching out 👍 

By default, RawRabbit uses `Newtonsoft.Json` with a type-handle set to `Auto` or `All` (depending on version of RawRabbit). If the `$type` property is present in the json payload it will be used when deserialize, which can be mismatched with what you try to deserialize to. I believe this is what you experience.

However, there is a problem with the approach you are describing. If a queue has multiple consumers RabbitMQ will deliver the message to one of the consumer in a round-robin manner. This means that if you have setup three subscribers on the same queue, (`SomethingCreated`, `SomethingUpdated` and `SomethingDeleted`) you will end up with three consumers that will get messages round robin, _independent of the type you define in RawRabbit_.

If three messages of type `SomethingCreated` are published, the services will get one message each. After that, hell brakes loose: something will go wrong either in deserializing it or if the deserialization worked the handler for `SomethingDeleted` will be invoked based on `SomethingCreated`.

Event sourcing and eventual consistency is commonly used in distributed system, but perhaps your requirements hinders you from such approach.

Hope this helps!

**Comment by MrGlenThomas** [comment]
Thanks @pardahlman I think will figure out a way of handling event ordering without using a single queue.

**Comment by pardahlman** [comment]
Ok, perfecto 👌 - closing this now!

**Comment by malamleh93** [comment]
Hi @MrGlenThomas,
I was wondering if you were able to figure out a way to implement the requirement mentioned above. I have similar requirements and I would be thankful for your help. 

Thanks,
Mohammad.

**Comment by blalonde** [comment]
Hi we were also wondering if it was possible to subscribe to multiple messages on the same queue.
If I say 
await busClient.SubscribeAsync<Message1>(
                async msg =>
                {
                    await Task.Run(() => callback1(msg));
                },
                ctx => ctx
                    .UseSubscribeConfiguration(
                        cfg => cfg
                            .Consume(
                                c => c
                                    .WithRoutingKey(routingKey)
                                    .WithPrefetchCount(2)
                                    .WithNoLocal(false))
                            .FromDeclaredQueue(
                                q => q
                                    .WithName(queue))
                            .OnDeclaredExchange(
                                e => e
                                    .WithName(exchange)
                                    .WithType(ExchangeType.Topic))));

await busClient.SubscribeAsync<Message2>(
                async msg =>
                {
                    await Task.Run(() => callback2(msg));
                },
                ctx => ctx
                    .UseSubscribeConfiguration(
                        cfg => cfg
                            .Consume(
                                c => c
                                    .WithRoutingKey(routingKey)
                                    .WithPrefetchCount(2)
                                    .WithNoLocal(false))
                            .FromDeclaredQueue(
                                q => q
                                    .WithName(queue))
                            .OnDeclaredExchange(
                                e => e
                                    .WithName(exchange)
                                    .WithType(ExchangeType.Topic))));

Won't it call callback1 when receiving message1 and callback2 when receiving message2 ?
We end up trying to deserialize message1 when receiving message2 and trying to call callback1.

Note that we have a custom xml serializer. The serializer succeeds in deserializing the message2, although it fails when trying to convert it to type message1, since the type is returned by

var messageType = GetMessageType(context);
return Serializer.Deserialize(messageType, bodyBytes);

and the context in the BodyDeserializationMiddleware is the one from the first subscription...

We're trying to use the one queue multiple message types pattern since we have a legacy MQ wrapper which is setup like that and would like to keep the system as is (if possible) since we have a single exchange and over 200 message types on about 30 queues.

Now maybe are actual configuration is not the recommended MQ configuration.
Could you please clarify ?

Thanks
