### ISSUE TITLE
HttpContext null when registering rawrabbit

### ISSUE THREAD

**Issue by jayrulez** [pardahlman/RawRabbit#262]
I am getting this exception when running my asp.net core 2.0 application:

```
Exception thrown: 'System.NullReferenceException' in Senit.dll
RawRabbit.Enrichers.HttpContext.PipeContextHttpExtensions.**GetHttpContext**(...) returned null
```

This is my code for registering RawRabbit:

```c#
services.AddRawRabbit(new RawRabbitOptions
            {
                ClientConfiguration = GetRawRabbitConfiguration(),
                Plugins = p => p
                    .UseGlobalExecutionId()
                    .UseHttpContext()
                    .UseMessageContext(ctx => new MessageContext
                    {
                        Source = ctx.GetHttpContext().Request.GetDisplayUrl(),
                        ExecutionId = ctx.GetGlobalExecutionId()
                    })
                    .UseAttributeRouting()
                    .UseStateMachine()
            });
```

Any idea what might be wrong here?

The null reference exception is thrown here:

```c#
.UseMessageContext(ctx => new MessageContext
                    {
                        Source = ctx.GetHttpContext().Request.GetDisplayUrl(),
                        ExecutionId = ctx.GetGlobalExecutionId()
                    })
```

**Comment by pardahlman** [comment]
Hi, @jayrulez - thanks for reporting this! I've tried to reproduce this myself by:

* Changing target framework to 2.0
* Upgrade all AspNetCore package to 2.0
* [Update](https://github.com/pardahlman/RawRabbit/commit/c2e788b37cd8197e3de12186c8b0cb1c12f5d4a7) the sample app to use a message context similar to yours.

However, it works as expected for me. Have a look at the update sample app and see if there is anything you've missed. If it still doesn't work, the perhaps you could provide me with a small sample app where the problem occurs!

Hope this helps!

**Comment by jayrulez** [comment]
I've looked over it. I'm not seeing what I'm doing differently.

The sample app works fine but mine has the issue.

The code is here: https://github.com/jayrulez/RawRabbitTest

Thank you for checking it out.

**Comment by jayrulez** [comment]
@pardahlman have you had a chance to look at this?

Regards

**Comment by pardahlman** [comment]
Unfortunately, no. If this is an blocking issue for you, perhaps you can use [the explicit message context approach](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/Enrichers/MessageContextTests.cs#L67) and create the context in the controller, where you have the http context.

**Comment by jayrulez** [comment]
I no longer get this error with the latest build. We can close for now.

Also, thank you very much for the quick work on the other issues.

Much appreciated.

**Comment by pardahlman** [comment]
Hello @jayrulez - no worries! I'm glad this problem is solved, even though it wasn't addressed 😉 .
Cheers!
