### ISSUE TITLE
Beta 9: Specify pipeline plugins per queue

### ISSUE THREAD

**Issue by msnelling** [pardahlman/RawRabbit#264]
Is there a way to specify the serialization plugin on a per-queue basis? Currently I'm using the following Ninject code to bind my protobuf serialiser plugin, however there are other queues that will need the default JSON serialiser.
```
var connectionString = ConfigurationManager.ConnectionStrings["RabbitMQ"];
var config = ConnectionStringParser.Parse(connectionString.ConnectionString);

Kernel.Bind<RawRabbitOptions>()
    .ToConstant(
        new RawRabbitOptions
            {
                ClientConfiguration = config,
                Plugins = p => p.UseProtobuf()
            });
```

**Comment by pardahlman** [comment]
It is nothing that will be shipped in RawRabbit. However, it should be fairly easy to implement your own middleware that does this. I've created a gist that shows you how to register a per call specific serializer: https://gist.github.com/pardahlman/e26c02643785e94f52ba60641c241fcb.

It will allow you to do the following:

```csharp
_client = RawRabbitFactory.CreateSingleton(new RawRabbitOptions
{
    Plugins = p => p.UseCustomerSerializerOverride()
});
await _client.SubscribeAsync<ValuesRequested>(
        async r => new Ack(),
        ctx => ctx.UseSerializer(new JsonSerializer(new Newtonsoft.Json.JsonSerializer()))
);
```

I might use this as an exanple on how to extend the client in the documentation, in which case you would get more details on the ideas behind it. However, I think you should be able to makes sense of it.

**Comment by pardahlman** [comment]
Another option, of course, is to register two `IBusClient`s with different serializers registered.

**Comment by pardahlman** [comment]
Some documentation on the topic: https://github.com/pardahlman/RawRabbit/blob/2.0/docs/getting-started/modify-pre-defined-operations.md

**Comment by msnelling** [comment]
Thanks, this is exactly what I was looking for.
