### ISSUE TITLE
Custom IConnectionFactory in 2.x

### ISSUE THREAD

**Issue by cocowalla** [pardahlman/RawRabbit#267]
I need to use a custom `IConnectionFactory`, to support login with SSL certificates.

I could do this in version 1.x by registering `IConnectionFactory` with my IoC container, but when doing this in 2.x it seems to be ignored and I always get a `ConnectionFactory` instead of my custom factory.

In `RawRabbitDependencyRegisterExtension.AddRawRabbit` this seems to be baked in - what is the recommend way to specify your own `IConnectionFactory`?

**Comment by pardahlman** [comment]
Hi @cocowalla - thanks for reaching out.

You should be able to register any custom implementation of internal RawRabbit services. Before I go into depth how do go about this: have you looked at the [`Ssl` property in `RawRabbitConfiguration`](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit/DependencyInjection/RawRabbitDependencyRegisterExtension.cs#L44)? It is used to configure SSL - perhaps it is enough for you?

The general syntax for register custom implementations of internal services are

```csharp
_client = RawRabbitFactory.CreateSingleton(new RawRabbitOptions
{
    DependencyInjection = ioc => ioc
        .AddSingleton<IConnectionFactory, CustomConnectionFactory>()
});
```

Let me know if this solves your problem!

**Comment by cocowalla** [comment]
Thanks for the super quick response!

The `Ssl` property isn't *quite* enough, as you also have to use set `ConnectionFactory.AuthMechanisms` to contain an `ExternalMechanismFactory` - otherwise it will still try to use the `PLAIN` mechanism (username & password).

Using the `DependencyInjection` property on `RawRabbitOptions` does indeed solve my problem, thanks!

I'm a bit confused on how the DI story in general works for 2.x though - you seen to be able to specify `IDependencyRegister` and `IDependencyResolver` instances (although the Ninject adapter only seems to specify the latter, while the Autofac once specified both) - but I'm not clear how these are used if you have to register custom implementations using `RawRabbitOptions.DependencyInjection`?

**Comment by pardahlman** [comment]
Great question!

One of the key ideas behind RawRabbit is that it should be easy to customize its default behavior. An example of this is how [operations/pipes can be replaced or updated](https://github.com/pardahlman/RawRabbit/blob/2.0/docs/getting-started/modify-pre-defined-operations.md).

Opening up for users to replace internal services is another piece of the puzzle. This is done by exposing actions for `IDependencyRegister` in `RawRabbitOptions`. There is an [_very_ naive dependency injection implementation](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit/DependencyInjection/SimpleDependencyInjection.cs) that is used in the `RawRabbitFactory`. The factory has two methods for different scenarios:

1. `CreateSingleton` which returns a disposable bus client. It disposes all dependencies when the client is disposed.
2. `CreateInstanceFactory` which returns an `InstanceFactory` that in turn can create normal instances of the client. The instance factory can be gracefully shutdown calling `ShutdownAsync` that cancels consumers but waits for RPC requests etc.

The `RawRabbitFactory` is a good match for small utilities without any IoC framework.

Let's assume that the application uses Autofac as DI framework. The package `RawRabbit.DependencyInjection.Autofac` includes an extension method that allows you to register RawRabbit from the `ContainerBuilder`

```
var builder = new ContainerBuilder();
builder.RegisterRawRabbit();
```

This call registers all of RawRabbit's internal dependencies in the application container (which is a good thing, as these framework typically are mature IoC frameworks). The fact that the internal services are registered means that they can be resolved in any part of your application. So if you want to use the InstanceFactory to gracefully shutdown the client, just inject `IInstanceFactory` in the constructor or a class and dispose away.

If, for some reason, you don't want to register RawRabbit internal services in your IoC container, you could do something like this

```
var builder = new ContainerBuilder();
var builder = new ContainerBuilder();
builder
    .Register<IInstanceFactory>(c => RawRabbitFactory.CreateInstanceFactory())
    .SingleInstance();
builder
    .Register<IBusClient>(c => c.Resolve<IInstanceFactory>().Create());
```

Hope this makes sense!

**Comment by cocowalla** [comment]
Thanks for explaining!
