### ISSUE TITLE
Messages queued when the broker goes down in 2.x

### ISSUE THREAD

**Issue by cocowalla** [pardahlman/RawRabbit#271]
I'm using RawRabbit 2.x with pub/sub.

When the broker goes down, calls to `PublishAsync` seem to queue messages for sending when the broker comes back up - is there any way to configure this?

1. For some publishers, I'd like to set a limit on the queue size, and have messages dropped when the queue is full
2. For some publishers, I'm like to not queue messages at all (such as application 'heartbeat' messages; there is no value in buffering these)

Something else I noticed - when the broker goes down, there doesn't appear to be any notification of this - I don't see anything about it from RawRabbit getting logged by the logging framework I use. Is this expected?

**Comment by pardahlman** [comment]
Top of the morning, @cocowalla  ☕️ 

This relates to an issue that you raised last year: https://github.com/pardahlman/RawRabbit/issues/143#issuecomment-268196645

At the moment, I don't see any reason to implement custom logic for this scenario. You should be able to control publish flow by providing a cancellation token to the publish calls and check the status of the returned task. Alternatively, this can be handled with some sort of custom middleware (I might be able to point you in the right direction), but from the top of my mind it would be very custom as each operation in RawRabbit is atomic, and what you are asking for is something that keeps track of previous operations state/result.

**Comment by cocowalla** [comment]
On reflection, I think you're right - leaving it to the caller allows for the greatest flexibility. I'm able to buffer, timeout or limit the number of concurrent tasks using a combination of the returned tasks and cancellation tokens.
