### ISSUE TITLE
Typo in RawRabbit.Common.NamingConvetions and INamingConvetions

### ISSUE THREAD

**Issue by brettnagy** [pardahlman/RawRabbit#28]
There is a 'n' missing from 'Convetions' in NamingConvetions.

**Comment by pardahlman** [comment]
Hi @brettnagy -- thanks for reporting this. Feel free to create a pull request to [`release/1.8.3`](https://github.com/pardahlman/RawRabbit/tree/release/1.8.3) and it will be part of the upcoming release.

**Comment by pardahlman** [comment]
Fixed as of PR #29
