### ISSUE TITLE
How create a queue ? 

### ISSUE THREAD

**Issue by karimflaction** [pardahlman/RawRabbit#281]
Hello, 

I'm doing a project and I don't know how create a queue... I know how receive a queue.

I tested this : 
`return BusClientFactory.CreateDefault( ioc => ioc.AddSingleton<IConfigurationEvaluator, AttributeConfigEvaluator>());`

But I cannot specify my configuration if I do this 

My configuration : 
`_config = new RawRabbitConfiguration
            {
                Username = "guest",
                Password = "guest",
                Port = 32780,
                VirtualHost = "vhost",
                Hostnames = { "rabbit-mq" }
            };`

I have too a class with my queue : 
`[Queue(Name = "test_queue", Durable = false)]
 [Exchange(Name = "test_exchange", Type = RawRabbit.Configuration.Exchange.ExchangeType.Topic)]
[Routing(RoutingKey = "test_key", NoAck = true)]
    public class BasicMessage
    {
        public string Message { get; set; }
    }`

How can I create a queue and set a configuration ? 

Somebody can help me ? 

Thank you,

**Comment by pardahlman** [comment]
Hello @karimflaction,

All topology features needed to perform an operation (such as publish or subscribe) will be created when performing the operation. So, for your example, the exchange `test_exchange` and `test_queue` will be declared when a message of type `BasicMessage` is subscribed to.

It looks like you are using version 1.10.x of the client, so you could look at the sample projects here: https://github.com/pardahlman/RawRabbit/tree/stable/sample. There is also documentation available here http://rawrabbit.readthedocs.io/en/master/Getting-started.html#messaging-pattern

Hope this helps!

**Comment by karimflaction** [comment]
Hello @pardahlman 

Tank you for you answer ;) I had already read the documentation. I followed your example and I did this : 

![image](https://user-images.githubusercontent.com/32644020/31373207-7554afd8-ad99-11e7-83ba-423cefa20b06.png)

I have my configuration in the file .json but as you can see I have a problem, the method .SetBasePath and .AddJsonFile doesn't work.

Do you have an idea ? 

Thank you

**Comment by karimflaction** [comment]
Oh I found this problem myself :)

But I have an another problem, when I start the application stop when I call the json file. I have this error : 

_System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred. (One or more errors occurred. (The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'test_queue_testrabbitmq_receiver' in vhost 'vhost': received 'false' but current is 'true'", classId=50, methodId=10, cause=))
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at RawRabbit.Operations.Subscriber`1.SubscribeAsync[T](Func`3 subscribeMethod, SubscriptionConfiguration config)
   at RawRabbit.Common.BaseBusClient`1.SubscribeAsync[T](Func`3 subscribeMethod, Action`1 configuration)
   at TestRabbitMq.Receiver.ConsoleAppRunner.<StartAsync>d__0`1.MoveNext() in C:\_TestRabbitMq-RawRabbit\rawrabbit-playground\TestRabbitMq.Receiver\ConsoleAppRunner.cs:line 28
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at TestRabbitMq.Receiver.Program.Main(String[] args) in C:\_TestRabbitMq-RawRabbit\rawrabbit-playground\TestRabbitMq.Receiver\Program.cs:line 35

Inner Exception 1:
AggregateException: One or more errors occurred. (The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'test_queue_testrabbitmq_receiver' in vhost 'vhost': received 'false' but current is 'true'", classId=50, methodId=10, cause=)

Inner Exception 2:
OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'test_queue_testrabbitmq_receiver' in vhost 'vhost': received 'false' but current is 'true'", classId=50, methodId=10, cause=
_

Can you help me ? 

If you must have something to understand my problem i can give you all :)

**Comment by pardahlman** [comment]
Hello again,
Reading the exception closely it says: _"PRECONDITION_FAILED - **inequivalent arg 'durable'** for queue 'test_queue_testrabbitmq_receiver' in vhost 'vhost': **received 'false' but current is 'true'**"_. This means that the queue `test_queue_testrabbitmq_receiver` is already declared in the broker. If you are new to RabbitMQ I suggest that you take a look at the [C# tutorial](https://www.rabbitmq.com/tutorials/tutorial-one-dotnet.html) that explains some basic concepts.

**Comment by karimflaction** [comment]
Thank you for your help :)

I have a last question. I create my queue and I receive it, but it create a lot of connections and I don't understand why. 

This is my code to receive : 

![image](https://user-images.githubusercontent.com/32644020/31433531-f36c901c-ae79-11e7-9318-7646899d04d6.png)

But it create a lot of connections and **channel** like this : 

![image](https://user-images.githubusercontent.com/32644020/31433601-24f9efc6-ae7a-11e7-8e60-2a5d4a585f4b.png)

How can I do to have one channel for a queue ? Thank you :)

**Comment by pardahlman** [comment]
It is difficult to answer that question based on your code snippet, is `RabbitHelper` a wrapper class? I'm guessing that you are creating multiple instances of `IBusClient`, which should be registered as a singleton if resolved from the factory.

**Comment by karimflaction** [comment]
Yes, 

That is my class : 

![image](https://user-images.githubusercontent.com/32644020/31434378-81ab7102-ae7c-11e7-9430-a3888dc55169.png)

I change this : 
![image](https://user-images.githubusercontent.com/32644020/31434404-9a27958a-ae7c-11e7-9c63-cc28295832d7.png)

I add the var test but it changed nothing 

My BasiscMessage class
![image](https://user-images.githubusercontent.com/32644020/31434486-cc29d08e-ae7c-11e7-8c38-bb15ef14c7d7.png)

And my configuration in .json
![image](https://user-images.githubusercontent.com/32644020/31434507-db6f2364-ae7c-11e7-857d-32fa9d0fdb68.png)

**Comment by pardahlman** [comment]
What you are actually doing is setting up _multiple_ subscriptions within your while-loop. If you want to perform multiple operations at the same time, have a look at these tests: https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/PublishAndSubscribe/MultipleOperationsTests.cs#L11

Note that the setup only does `SubscribeAsync` once.

**Comment by karimflaction** [comment]
I test it like that: 

![image](https://user-images.githubusercontent.com/32644020/31441720-6976af62-ae94-11e7-9b87-d2fcba028499.png)

But nothing :(

**Comment by pardahlman** [comment]
Yeah, so what I'm saying is: check how it is done in the tests I pointed to. If you have `SubscribeAsync` within an infinite while loop, you are going to get multiple consumers.
