### ISSUE TITLE
Disposed ack timer

### ISSUE THREAD

**Issue by wicharypawel** [pardahlman/RawRabbit#282]
#question
Hello,
I have started recently working with RawRabbit 1.10.4 and I do worry about stacking messages that I see while debugging in console, I would appreciate any help.

The message is:
[time][numberZ][DEBUG][PublishAcknowledger]: Disposed ack timer for numberX/numberY

Question1. Every few publishes I see a growing list of those messages, do I miss to ack something? (I see no errors but stacking messages worry me.)

Question2. Can someone explain to me what are the numbers Z, X and Y ? Where did they come from, are those channels number or something like this?

Thanks in advance

**Comment by pardahlman** [comment]
Hello @pablites,

The messages you see is for the _publisher acknowledgement_, which is the ack that the broker sends to the client, telling the client that the message has been published. You can read more about RawRabbit's publisher ack [in the documentation](http://rawrabbit.readthedocs.io/en/master/Publisher-Acknowledgements.html) and about publish ack in general over at [RabbitMQ's site](https://www.rabbitmq.com/confirms.html). So to summarize: it is a _good_ thing that you get publish acks :wink:

As for the numbers, they are:
* Z: thread id
* X: delivery tag
* Y: channel number

You can read more about the two last ones here: https://www.rabbitmq.com/amqp-0-9-1-reference.html

**Comment by wicharypawel** [comment]
That's what I was looking for.
Thank you @pardahlman
