### ISSUE TITLE
How do RPC ? 

### ISSUE THREAD

**Issue by karimflaction** [pardahlman/RawRabbit#283]
Hello, 

I've a project and I have some queues. But now I want to do some Request/Reply. 

I read all your documentation, I download your solution on github to try to understand how to make RPC. 
I have a queue and I want to respond to my sender. 

I used your documentation to do that but it doesn't work. I don't understand what is the BasicRequest.

Do you have an another example which use a queue ?

Thank you for your time

**Comment by pardahlman** [comment]
Hello, @karimflaction - are you refering to code like this

```csharp
var response = await busClient.RequestAsync<BasicRequest, BasicResponse>(new BasicRequest());
```

The `BasicResponse` is the expected response type of the request. It is defined here: https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/TestMessages/BasicResponse.cs

**Comment by karimflaction** [comment]
Hello, 

Thank you @pardahlman  I found my error. Thank you
