### ISSUE TITLE
The queue doesn't have the correct Name

### ISSUE THREAD

**Issue by karimflaction** [pardahlman/RawRabbit#285]
Hello ! 

I'm sorry to disturb you once again but I have a problem. I create my queue in the class "BasicMessage" like this : 
![image](https://user-images.githubusercontent.com/32644020/31532909-41223a7e-aff0-11e7-9a56-ddc5249c6c9c.png)

I noticed that the binding was made at the time of the reciever when I do this : 
![image](https://user-images.githubusercontent.com/32644020/31532954-730f7042-aff0-11e7-91f7-69feeb789544.png)

I noticed too that de name of the queue "test_queue" is not correct when I check in the RabbitMq-Management : 
![image](https://user-images.githubusercontent.com/32644020/31533001-9fabc10a-aff0-11e7-9f74-9cbfa9dc4733.png)

With my test, I noticed that my queue is not used. When I change the name of the queue the message work but if I change the name of the exchange, the message doesn't work. 

How can I do the binding at the sender ? Why the name is not correct ? Why the message passes even if the name of the queue is not correct?

Thank you for your time and your help

**Comment by pardahlman** [comment]
Are you refering to the queue suffix `testrabbitmq_receiver`? It is [documented here](http://rawrabbit.readthedocs.io/en/master/Multiple-Subscribers-for-Messages.html). There is also some information on how to remoev the queue suffix.
