### ISSUE TITLE
Setting x-max-length of queue

### ISSUE THREAD

**Issue by Towmeykaw** [pardahlman/RawRabbit#287]
Hello! Im having issues setting the x-max-length argument of a queue.
Im using the following to get messages form an exchange but i cant set a max value of the queue that gets created. 
`.UseSubscribeConfiguration(cfg => cfg
 .OnDeclaredExchange(e => e
                        .WithName("bus2center")
                        .WithType(ExchangeType.Topic))
.Consume(c => c
                        .WithRoutingKey("*.tracking.position"))
                `

**Comment by pardahlman** [comment]
Hello @Towmeykaw ,

Have you tried using the `WithArgument` configuration

```csharp
.FromDeclaredQueue(q => q
    .WithName("custom_queue")
    .WithAutoDelete()
    .WithArgument("x-max-length", 10))
```

**Comment by Towmeykaw** [comment]
I was pretty sure i had tried that. But it worked perfectly! 
Thanks! 👍
