### ISSUE TITLE
Lost Messages with Retry.In

### ISSUE THREAD

**Issue by ThomasOpiolka** [pardahlman/RawRabbit#294]
While testing some scenarios I had the following Issue with the 2.0.0-rc1 version:

```
            bus.SubscribeAsync<TCommand> (async (msg) => {
                try{
                    await handler.HandleAsync (msg); 
                    Console.WriteLine($"ACK"); 
                    return new Ack();                    
                }catch(Exception){                    
                    Console.WriteLine($"Retry"); 
                    return Retry.In(TimeSpan.FromSeconds(30));                    
                }
            }
```

the handler.HandleAsync method throws an instant Exception. The Console Logs the Retry Message for every Message sent ( 10 in a row ). But only around 4 to 9 Messages get really requeued in RabbitMQ.

Inserting an Thread.Sleep(200) before the Throw Exception will fix this issue.
Looks like some race condition of some sort.

Any Ideas?

**Comment by ThomasOpiolka** [comment]
using 
`Plugins = p => p.UseGlobalExecutionId()`
seems to fix that issue.

**Comment by arrkaye** [comment]
@pardahlman Hey mate, Is the GlobalExecutionId required for the retry functionality to work?
