### ISSUE TITLE
DeclareExchangeAsync should have a method that accepts ExchangeDeclaration?

### ISSUE THREAD

**Issue by hopengfoong** [pardahlman/RawRabbit#295]
DeclareQueueExtension has an extension method that accepts a `QueueDeclaration`. 
https://github.com/pardahlman/RawRabbit/blob/e4b6081ee3d057bfaa4b634d92e5a23a7d0de6c1/src/RawRabbit.Operations.Tools/DeclareQueueExtension.cs#L17

Should DeclareExchangeExtension have a similar method? Right now it only has this method: 
https://github.com/pardahlman/RawRabbit/blob/e4b6081ee3d057bfaa4b634d92e5a23a7d0de6c1/src/RawRabbit.Operations.Tools/DeclareExchangeExtension.cs#L16 

Also, I've noticed that pipe here is named `DeclareQueueAction`. Should it be `DeclareExchangeAction` instead? 
https://github.com/pardahlman/RawRabbit/blob/e4b6081ee3d057bfaa4b634d92e5a23a7d0de6c1/src/RawRabbit.Operations.Tools/DeclareExchangeExtension.cs#L12-L14

**Comment by pardahlman** [comment]
Hello @hopengfoong - thanks for reaching out. You are right on all points, feel free to submit a PR that fixes this!

**Comment by hopengfoong** [comment]
@pardahlman  Thanks for the reply! :) 
I've submitted the PR here  https://github.com/pardahlman/RawRabbit/pull/296 :)
