### ISSUE TITLE
Declare / maintain Exchange & Queue separated from Subscriber & Publisher mechanisme

### ISSUE THREAD

**Issue by vianeykurniawan** [pardahlman/RawRabbit#302]
Hello, i want to asking you about declaring exchange & queue but in separated way from subscriber and publisher mechanisme, so i can use / maintain by my self processes (web / console / service) as publisher & subscriber pointing into specific exchange or queue which has been create. As my understanding publisher can create exchange by default following the namespace of project, and subscriber will creating both Exchange & queue when we invoke it . Thank you for your help.

**Comment by vianeykurniawan** [comment]
FYI, i use RawRabbit 2.0 rc by the way.

**Comment by pardahlman** [comment]
Hi @vianeykurniawan - thanks for reaching out!

Looks like you are looking for the `RawRabbit.Operations.Tools` package, which contains operations to declare queues, exchange and bind them. There are some example in the integration tests, for example [here](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/Enrichers/GlobalExecutionIdTests.cs#L42-L46)

```csharp
await busClient.DeclareQueueAsync(new QueueDeclaration
{
    Name = "take_all",
    AutoDelete = true
});
```

Hope this helps!

**Comment by vianeykurniawan** [comment]
Hi  @pardahlman  Thank you for your fast response. So, i will declare exchange & queue using RawRabbit.Operations.Tools nuget package, and when i call or invoke publisher & subscriber i also set the configuration via UsePublishConfiguration & UseSubscribeConfiguration pointing to the existing Exchange & Queue. My next questions, what's the different between Consumer Configuration & Subscriber Configuration ?  Great architecture BTW. Thanks for your help.

**Comment by pardahlman** [comment]
Correct, here's an example on how you would publish a message on an existing exchange

```csharp
publisher.PublishAsync(new BasicMessage(), ctx => ctx
    .UsePublishConfiguration(cfg => cfg
        .OnExchange("predeclared_exchange")
        .WithRoutingKey("some.routing.key")
    )
);
```

(If you instead use `.OnDeclaredExchange(...)` the exchange will be declared before the message is published. Note that an exception will be thrown if a message is published on a non-existing exchange 😉.

As to your other question: `ConsumerConfiguration` is the configuration passed to the `IConsumerFactory` to create the consumer. `SubscriptionConfiguration` is part of the legacy support (compatibility with 1.x of the client).

**Comment by vianeykurniawan** [comment]
Great !!!. Thank you
