### ISSUE TITLE
Enrichers, ZeroFormatter

### ISSUE THREAD

**Issue by LordMike** [pardahlman/RawRabbit#306]
I copied the Protobuf formatter and tailored it for ZeroFormatter. Should I make a PR that adds it to this repo?

Also. ZeroFormatter _only_ has generic methods, they do not provide anything receiving `Type` parameters - so I had to use reflection to generate these invocations on the fly. I don't think theres any workaround for this at present.

**Comment by pardahlman** [comment]
Yes please 👏 😄
