### ISSUE TITLE
Make BasicDeliverEventArgs available for subscriptions

### ISSUE THREAD

**Issue by fgieseke** [pardahlman/RawRabbit#307]
Is there a possibility to access the BasicDeliverEventArgs when receiving a message a consumer subscribed on? I need to read the routing key the message was send with. Also the headers have to be accessible, to build up some custom business-logic. 
Is there already such a feature? I couldn't find it...

**Comment by pardahlman** [comment]
If you're using the message context enrichers you should be able to [do something like this](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/Enrichers/MessageContextTests.cs#L243-L247) to get hold of the delivery args.

**Comment by pardahlman** [comment]
If you have business logic that you want to extract in a structured way, then perhaps a custom message context could be used - [here](https://github.com/pardahlman/RawRabbit/blob/2.0/sample/RawRabbit.AspNet.Sample/Startup.cs#L48-L54) is an example where a context is built up from properties in the pipe context - basic event args are there, too.

**Comment by fgieseke** [comment]
Thanks for the examples. We're still on version 1.10.4, so the examples don't fit. But our solution is to extend the AdvancedMessageContext adding property "EventArgs". Our custom ContextEnhancer then sets in WireUpContextFeatures the EventArgs to the BasicDeliverEventArgs provided.

Wouldn't this be a feature for the build in AdvancedMessageContext?

**Comment by pardahlman** [comment]
I think that sounds like a good approach 👌 .

**Comment by fgieseke** [comment]
It worked. We will be switching from version 1.x to 2.x. Is there a good introduction to the changes? Any hint would be apreciated. 




Thanks so far. 




Falko









On Tue, Feb 6, 2018 at 7:48 PM +0100, "Pär Dahlman" <notifications@github.com> wrote:












I think that sounds like a good approach 👌 .
