### ISSUE TITLE
Use SteelToe instead of Polly

### ISSUE THREAD

**Issue by VenkateshSrini** [pardahlman/RawRabbit#311]
Hi,

Is it possible to use SteelToe (http://steeltoe.io) instead of Polly. I ask this because  I want to use this on cloud foundry with .NET core. Please do let me know of the same

**Comment by cocowalla** [comment]
Polly handles transient-fault-handling (e.g. retries), whereas Steeltoe seems to be a large eco-system of cloud-related libraries. I guess you specifically meant [Netflix Hystrix](https://github.com/SteeltoeOSS/CircuitBreaker)?

In any case, RawRabbit is very extensible, and only uses Polly in an optional `RawRabbit.Enrichers.Polly` package. I see no reason why you couldn't try to create your own plugin, using `RawRabbit.Enrichers.Polly` as a guide?

Disclaimer: Not the author, just a happy user trying to help out ;)

**Comment by VenkateshSrini** [comment]
Yes exactly. Also circuit breaker patterns are present in steel toe is well
integrated with hystrix

**Comment by pardahlman** [comment]
Hi @VenkateshSrini - thanks for reaching out. Also, thanks for answering @cocowalla - much appreciated! I'm not too familiar with steeltoe, but it is as cocowalla says - it shouldn't be difficult to integrate its mechanisms to RawRabbit - you can look at the Polly package for inspiration!

**Comment by VenkateshSrini** [comment]
@pardahlman ,
I know polly and have also worked with it in many projects. I have no complaints against polly. The only ask if you could also probably add an "Use" method to steelToe it will be useful. At present their circuit breaker is well integrated with Eureka spring cloud services and provides the very much needed dash board. Otherwise give the steps to include the steel toe so that I will try out the same

**Comment by pardahlman** [comment]
Understood. Unfortunately, I'm very busy at the moment, but if you have knowledge in steel toe, perhaps you could look into integrating it with RawRabbit? 😄

**Comment by VenkateshSrini** [comment]
Definitely based on my bandwidth o will try it

**Comment by pardahlman** [comment]
Hi @VenkateshSrini - I'm closing this ticket for now. Feel free to reopen or reference it if you get around to create a PR. Thanks!
