### ISSUE TITLE
StateMachine Question

### ISSUE THREAD

**Issue by yang-cloudlet** [pardahlman/RawRabbit#322]
Thanks for making 2.0 happen, really looking forward to the offical release. While I am waiting for the documentation, do you mind if you can share a bit on how to use StateMachine? I am trying to copy the code from the integrated tests, I do not know how I can trigger the message to fire the state.

**Comment by pardahlman** [comment]
Hello @yangyu0311ugroop  👋 

Thanks for reaching out. The [documentation for the StateMachine operation](https://github.com/pardahlman/RawRabbit/blob/2.0/docs/operations/statemachine.md) is nothing much to see at the moment 😉. Know that this article will be written before 2.0 is release, you can keep track on #184 for documentation efforts.

Until then, I believe that the [test(s)](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/StateMachine/StateMachineTests.cs) and source code is the best sources to getting started with State Machine. Have you tried debugging the test case? You can also have a look at `MessageSequence` implementation, as it uses State Machine internally.

If messages doesn't trigger, perhaps you haven't [registered](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/StateMachine/StateMachineTests.cs#L23) a [trigger configuration](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/StateMachine/Generic/ProcessTriggers.cs).

Hope this helps!
