### ISSUE TITLE
Using BasicGetOperation with empty Queue throws a Null exception 

### ISSUE THREAD

**Issue by Ankurkh1** [pardahlman/RawRabbit#323]
https://github.com/pardahlman/RawRabbit/blob/e4b6081ee3d057bfaa4b634d92e5a23a7d0de6c1/src/RawRabbit.Operations.Get/GetOperation.cs#L22

Line 22 should test for nulls. Like how it does for GetOfTOperation 
DeliveryTagFunc = context => context.GetBasicGetResult()?.DeliveryTag ?? 0,

**Comment by pardahlman** [comment]
You are right - feel free to submit a PR for this 👍
