### ISSUE TITLE
Question reg. message attributes / arguments

### ISSUE THREAD

**Issue by LordMike** [pardahlman/RawRabbit#328]
Hey,

A message in rabbitmq can have key-value arguments, typically in the form "x-mykey = myvalue" -- is there a way to access these using RawRabbit?

Mike.

**Comment by LordMike** [comment]
Reading the docs leads me to believe I need to access a Message Context - but I can't find this in v2.0 -- at least the `Func<T, Context>` isn't available in f.ex. `SubscribeAsync`.

**Comment by pardahlman** [comment]
Top of the morning, @LordMike. Are you thinking about the message headers? They can be set like so

```cs
await publisher.PublishAsync(message, ctx => ctx
    .UsePublishConfiguration(cfg => cfg
        .WithProperties(properties => properties.Headers.Add("foo", "bar"))
));
```

HTH!

**Comment by LordMike** [comment]
And how would that look on the receiving end?

In this instance, I'm using MQTT to send messages to RabbitMQ, and would like to get f.ex. the client id or queue name (mqtt: topic name) that a given message had.

**Comment by ChristianSauer** [comment]
Hi,

I totally forgot to report a bug:

If you use an object as header, the publish silently never happens

 

e.g.

.WithProperties(properties => properties.Headers.Add("foo", SomeObj))

 

 

Von: Pär Dahlman [mailto:notifications@github.com] 
Gesendet: Montag, 12. März 2018 07:17
An: pardahlman/RawRabbit <RawRabbit@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [pardahlman/RawRabbit] Question reg. message attributes / arguments (#328)

 

Top of the morning, @LordMike <https://github.com/lordmike> . Are you thinking about the message headers? They can be set like so

await publisher.PublishAsync(message, ctx => ctx
    .UsePublishConfiguration(cfg => cfg
        .WithProperties(properties => properties.Headers.Add("foo", "bar"))
));

HTH!

**Comment by pardahlman** [comment]
@ChristianSauer thanks for chiming in 😉 . The `WithProperty` API is advanced in that it expose the underlying `BasicProperties` (from the official `RabbitMQ.Client`). The signature (that is, the fact that it exposes `IDictionary<string, object>`) is nothing something I can change. The header value is suppose to be a `byte[]`, which unfortunately isn't that clear. [Here's a middleware](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit/Pipe/Middleware/HeaderDeserializationMiddleware.cs) that RawRabbit uses for setting these headers.

As for the silent failing, that is something that we should report in a separate issue so that it can be tracked there.

**Comment by pardahlman** [comment]
@LordMike´, the way I see it you could either [inject the BasicDeliveryArgs](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/Enrichers/MessageContextTests.cs#L236) into the consumer, or - if it makes more semantic sense in your case - create a custom `MessageContext` class that is constructed with relevant header values. Have a look at the ASP.NET Core sample in this repo

```cs
services
  .AddRawRabbit(new RawRabbitOptions
      {
        ClientConfiguration = GetRawRabbitConfiguration(),
        Plugins = p => p
          .UseHttpContext()
          .UseMessageContext(c =>
          {
            return new MessageContext
            {
              Source = c.GetHttpContext().Request.GetDisplayUrl(),
              FooHeader = c.GetDeliveryEventArgs().BasicProperties["Foo"]
            };
          })
      })
```

**Comment by LordMike** [comment]
Hi again,

I've just noticed / realized that there is a `RawRabbit.Enrichers.MessageContext` package, along with a `RawRabbit.Enrichers.MessageContext.Subscribe` package - I've referenced both now.

In the code below, I followed your example and added a class with some property to it - but it doesn't seem like the `UseMessageContext` func is being called (also note that `BasicProperties` isn't indexable). Likewise, the context variable is null as shown.

I've noticed the `UseMessageContext` does not specify any requirements for the `MessageContext` class, other than it having a default constructor. Should it inherit from something?

![image](https://user-images.githubusercontent.com/1027111/37427138-af4eff82-27c8-11e8-9b28-7f5d5c444c37.png)

**Comment by pardahlman** [comment]
Good morning!

There are two related, but different concepts in play here. Normally, a message context is created when a message is published and just deserialized when it is consumed. By calling `UseMessageContext` in your plugin you are essentially saying that _this_ client should look for message context when receiving a message or create message context when publishing a message. The other concept is to build a message context based on properties in the `IPipeContext` that is passed around in the execution.

Now that I've read your scenario a bit closer, I believe that what you want to do is [what the second example](https://github.com/pardahlman/RawRabbit/blob/2.0/docs/enrichers/message-context.md#incomming-messages) in this section describes. As the producer in your case does not send any Message Context, you should be able to skip registering the message context plugin at all and just define a "pipe based" message context.

I know that the documentation is lagging behind, this should be addressed in #184

**Comment by LordMike** [comment]
I see, so the UseMessageContext on subscribe is for "deserializing" which we're just borrowing.

Observe that two extension methods for UseMessageContext exist, one in `RawRabbit.Enrichers.MessageContext.Subscribe` and one in `RawRabbit.Enrichers.MessageContext` - I took the one accepting a func as in the example... :)

Side question: I can see the `BasicDeliverEventArgs` also give me access to the body of the message (a byte array) - is it possible to not receive a message in `SubscribeAsync()`, but just the `BasicDeliverEventArgs` ?

In my use case, I'm going to be processing messages from IOT devices, each with a message body format this fits their use case. Adding a deserializer to the pipeline that would work for all cases doesn't seem feasible. I'm really liking RawRabbit for abstracting away all the setup, so I'd like to continue using it :)

I should be able to get all up and running using the `BasicDeliverEventArgs`. Thanks :)

**Comment by pardahlman** [comment]
I'm glad it worked out 👍. The Subscribe methods are focused on the generic argument of `<TMessage>` deriving topology and serialization out of the box. If you want to have a more fine-grained control over the consumer pipe, you could either build your own (not that difficult!) or use something like the [BasicConsumeAsync](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/Enrichers/GlobalExecutionIdTests.cs#L47) operation which gives you the delivery args right away.
