### ISSUE TITLE
Question: Headers Exchange

### ISSUE THREAD

**Issue by woellij** [pardahlman/RawRabbit#332]
Hi there.

First of all: Thanks for the intuitive framework. It makes working with RabbitMQ a breeze.

But: I have a question concerning Headers Exchange. We're planning to use it in a current project, but i can't seemt to Register for Messages with certain headers. I've figured out how to set the headers (via the properties) but can't register a handler, for certain headers.

A short example would be greatly appreciated.

Cheers

**Comment by pardahlman** [comment]
Hi @woellij - thanks for reaching out!

I'm afraid that RawRabbit does not support header exchange out of the box. This is definitely a feature that I will look into adding, but the best you can do today is to declare the topology with the underlying `IModel` ("channel") and then subscribe to messages without declaring any queue/exchange/binding.

```cs
IModel channel = await client.CreateChannelAsync();

// declare topology with channel

client.SubscribeAsync<BasicMessage>(basicMessage =>
{
  // subscribe
}, ctx => ctx
  .UseSubscribeConfiguration(cfg => cfg
    .Consume(c => c
      .FromQueue("queue")
      .OnExchange("exchange"))
  ));
```

HTH!

**Comment by woellij** [comment]
Added a pull request. Unfortunately i don't have the time to thuroughly test it ... but so far it is working well for us. #335

Would be cool if you found time to merge it and release it on nuget.  

Cheers

**Comment by shahabganji** [comment]
@woellij, @pardahlman 

May I ask you guys to provide a simple sample for the publish part, whatever I set it adds a routing key to the message and prevents using headers. That would be highly appreciated. :pray:

**Comment by shahabganji** [comment]
@woellij , @pardahlman ,

I guess that the publisher part should be something similar to the following, at least that worked for me, just out of curiosity, it also sets a ```routing_key``` of the payload type, in this case it is ```string```


```cs
Action<IPublishContext> publishContext = context => {
	context.UsePublishConfiguration(config => {
			config.OnExchange("exchange")
					.WithProperties(prop => {
	    				     prop.Headers.Add("x-match", "any");
   					     prop.Headers.Add("first-header", value1);
					     prop.Headers.Add("second-header", value2);
			});
		});
	};

// send the message: 
bus.PublishAsync("some message to send", publishContext);

```

Is there anything I missed?

**Comment by shahabganji** [comment]
> Hi @woellij - thanks for reaching out!
> 
> I'm afraid that RawRabbit does not support header exchange out of the box. This is definitely a feature that I will look into adding, but the best you can do today is to declare the topology with the underlying `IModel` ("channel") and then subscribe to messages without declaring any queue/exchange/binding.
> 
> ```cs
> IModel channel = await client.CreateChannelAsync();
> 
> // declare topology with channel
> 
> client.SubscribeAsync<BasicMessage>(basicMessage =>
> {
>   // subscribe
> }, ctx => ctx
>   .UseSubscribeConfiguration(cfg => cfg
>     .Consume(c => c
>       .FromQueue("queue")
>       .OnExchange("exchange"))
>   ));
> ```
> 
> HTH!

That creates a binding with ```routing_key``` I declared in the following way, did I miss anything?

```cs
Action<ISubscribeContext> context = (ctx) => {
	ctx.UseSubscribeConfiguration(config => {
		config.Consume(cns => {
			cns.OnExchange("exchange")
			     .FromQueue("sample.header.queue1")
			;
		});
	});
};

bus.SubscribeAsync(async (string payload) => {
	logger.Information("A message received: {@Payload}", payload);
}, context);
```

**Comment by shahabganji** [comment]
@pardahlman  Can you take a look at this thread and [this](https://github.com/pardahlman/RawRabbit/pull/335) pull request, please 🙏

**Comment by pardahlman** [comment]
Merged / thanks!
