### ISSUE TITLE
Consumer concurrancy throttle

### ISSUE THREAD

**Issue by afmuller** [pardahlman/RawRabbit#336]
#169 
With reference to issue169 (Consumer concurrancy throttle).
I am running RawRabbit v2.0.0 rc5. What NuGet packages do I need to install to get this to work?

```
await subscriber.SubscribeAsync<BasicMessage>(async message =>
{
	// do stuff
}, context: c => c.AddConsumeSemaphore(concurrency: 3));
```

I am battling to find the package which contains the extension method to get this to work. 

Sorry for the trouble.

**Comment by afmuller** [comment]
Is this the new extension method to use:

c.UseConsumerConcurrency(x)

**Comment by pardahlman** [comment]
Hello @afmuller - all methods related to consumer throttling is found in the `RawRabbit` package, see https://github.com/pardahlman/RawRabbit/blob/e4b6081ee3d057bfaa4b634d92e5a23a7d0de6c1/src/RawRabbit/Pipe/AddPropertyPipeContextExtensions.cs
