### ISSUE TITLE
Creating an extended client

### ISSUE THREAD

**Issue by knepe** [pardahlman/RawRabbit#338]
Hi
I'm struggling to create an extended client and I'm not sure how to fix it. I have followed the docs but there seem to be some breaking changes on how to create it. On my mobile now but basically what I have is a net core 2.0 Api project with Structuremap as DI. Can anyone just give me an example on how to do it, either with the DI extensions (services.AddRawRabbit) or just manually in some other class like a Controller, doesn't matter.

Thanks!

**Comment by pardahlman** [comment]
Hi @knepe, thanks for reaching out. If you are using the 1.x version of the client [this documentation](http://rawrabbit.readthedocs.io/en/master/Extending-RawRabbit.html#the-extendable-bus-client) might be helpful. You should also be able to [look at some of the integration tests](https://github.com/pardahlman/RawRabbit/blob/master/test/RawRabbit.IntegrationTests/Extensions/BulkGetTests.cs#L62) to see how the client is created.

The notion of extended client does not exist in 2.x of the client - here, all methods are in fact extension methods of `InvokeAsync`, see for example [here](https://github.com/pardahlman/RawRabbit/blob/2.0/docs/operations/publish.md) (WIP).

Hope this helps!

**Comment by knepe** [comment]
Thanks! Got it sorted with 2.x

**Comment by pardahlman** [comment]
Perfecto!
