### ISSUE TITLE
Fix Receive word misspellings

### ISSUE THREAD

**Issue by sayfulloev** [pardahlman/RawRabbit#348]
Noticed throughout the code the word `receive` is misspelled as `recieve`. NBD, just want to keep code tidy from this perspective as well.

**Comment by pardahlman** [comment]
Thanks a bunch for this. _Received_ and _third_ are two worlds that I just can't seem to spell correctly in the source code 😂

**Comment by pardahlman** [comment]
Thanks a bunch for this. _Received_ and _third_ are two worlds that I just can't seem to spell correctly in the source code 😂
