### ISSUE TITLE
Version 2.0 Release

### ISSUE THREAD

**Issue by msnelling** [pardahlman/RawRabbit#350]
Hi,
Do you have a date in mind on when you plan on releasing version 2.0?

**Comment by pardahlman** [comment]
Hello, not at the moment. The latest rc has been well received, apart from some long running scenarios. I want to address this before the actual release. However, I'm currently swamped with work and other obligations. It will not happen before the summer, I'm afraid :/

**Comment by tafs7** [comment]
@pardahlman Summer will be officially over in...3 days. Just wanted to see if you had any better thought on when 2.0 would release?

Also, have the issues regarding memory leaks, and also long running connections been addressed in 2.0?

**Comment by ChristianSauer** [comment]
I would welcome a rc-6 with all the changes that happened after rc-5.
