### ISSUE TITLE
Create a queue without subscription

### ISSUE THREAD

**Issue by ArtyomVoronov** [pardahlman/RawRabbit#351]
I'm going to create a queue for bulk-fetching messages and don't need any active subscriber.  How to declare a queue with a specified name?

**Comment by pardahlman** [comment]
top of the morning, @ArtyomVoronov - assuming you are using 2.x here. In that case you should be able to use the [`RawRabbit.Operations.Tools`](https://www.nuget.org/packages/RawRabbit.Operations.Tools/) operation to add `QueueDeclareAsync` like what [I'm doing in this test](https://github.com/pardahlman/RawRabbit/blob/e4b6081ee3d057bfaa4b634d92e5a23a7d0de6c1/test/RawRabbit.IntegrationTests/Enrichers/GlobalExecutionIdTests.cs#L42)

```csharp
await consumer.DeclareQueueAsync(new QueueDeclaration
{
    Name = "take_all",
    AutoDelete = true
});
```

Hope this helps!

**Comment by ArtyomVoronov** [comment]
Hi @pardahlman,
Thank you, it helps.
