### ISSUE TITLE
Auto-Queuenames collide if used from multiple Services

### ISSUE THREAD

**Issue by ChristianSauer** [pardahlman/RawRabbit#352]
Hi
we had recently a problem where build a base nuget package for a very common message in our infrastructure. This message is send and consumed by multiple services, but since the intent is totally different not every service can consume every message.

When RawRabbit generates the Queue Names, the names are just the class names (which is just SomethingMessage in every service, since they share the same nuget package), and now multiple subscribers share the same queue and hilarity ensues. We have just inherited the class in our services and thus created different names, but we feel that there should be a mechanism to add the service name to the Queue Name.

I have traced it to the method CreateShortAfqn and would propose that we add an option to use a generic prefix, e.g. a configurable service name from the configuration.

**Comment by pardahlman** [comment]
Hello,
It sounds like you are using v 2.x of RawRabbit. You could try to use the [`RawRabbit.Enrichers.QueueSuffix`](https://www.nuget.org/packages/RawRabbit.Enrichers.QueueSuffix), that allows you to add application suffixes (poor support for all .NET Core hosting scenarios), server name suffix or custom prefixes.  See [the tests here](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/Enrichers/QueueSuffixTests.cs#L14) for more information!

Hope this helps!
