### ISSUE TITLE
Consuming messages one at a time from the queue

### ISSUE THREAD

**Issue by arrkaye** [pardahlman/RawRabbit#377]
Hi,

I have the following code, with the intention that each message is taken in turn and handled by the Invoke(), before the next one is processed.

Please can you help me with what I'm doing wrong. I've been unable to figure it out from the docs.

`public async Task Enqueue(T t)
{
	await _busClient.PublishAsync(t,
		c => c.UsePublishAcknowledge(false).UsePublishConfiguration(a => a.OnDeclaredExchange(e => e.WithName(t.GetType().GetExchangeName()))));
}`

`public async void Start()
{
	await _busClient.SubscribeAsync<T>(async t =>
	{
		try
		{
			await OnMessage?.Invoke(t);
			return new Ack();
		}
		catch (RetryLaterException rle)
		{
			return Retry.In(rle.Retry);
		}
		catch
		{
			return Retry.In(_retry);
		}
	}, c => c.UseSubscribeConfiguration(s => s.FromDeclaredQueue(e => e.WithName(typeof(T).GetExchangeName())).OnDeclaredExchange(e => e.WithName(typeof(T).GetExchangeName()))));
}`

**Comment by pardahlman** [comment]
It sounds like you want to use the set `ConsumerConcurrency`, see [this test case](https://github.com/pardahlman/RawRabbit/blob/6229f5285d2cb5b9370ebfb616de2977d0386e24/test/RawRabbit.IntegrationTests/Features/ConsumeThrottleTests.cs#L55) for an concrete example

```csharp
await subscriber.SubscribeAsync<BasicMessage>(message =>
{
    // Handle here
}, c => c.UseConsumerConcurrency(1));
```
Hope this helps!

**Comment by riazkarim** [comment]
Amazing! Thanks!

**Comment by arrkaye** [comment]
Amazing, Thanks!
