### ISSUE TITLE
How to publish to queue with name suffix

### ISSUE THREAD

**Issue by mersadk** [pardahlman/RawRabbit#390]
I'm subscribing to queue and specifying name suffix for queue name. 
```
_busClient.SubscribeAsync<ToCrawlQueueMessage>(
	async (message, context) =>
	{
		// Execute code
	},
	ctx =>
	{
		ctx.WithQueue(q => q.WithNameSuffix(shopSlug));
	}
);
```

How can I add this suffix to queue name while publishing message?

**Comment by pardahlman** [comment]
Hi @mersadk - In RabbitMQ, messages are published to exchanges not queues - consider checking the [official tutorial](https://www.rabbitmq.com/tutorials/tutorial-one-dotnet.html) for basic concepts 👍
