### ISSUE TITLE
KeyNotFoundException during Request/Response

### ISSUE THREAD

**Issue by crillemon** [pardahlman/RawRabbit#51]
When doing RPC calls in quick succession the consumer is removed and a new one is not created and the KeyNotFoundException is thrown.

I've pinpointed the problem to `RawRabbit.Operations.Requester.cs` in the `GetOrCreateConsumerForType` method. There is a check to verify that `_typeToConsumer` contains the correct response type but the `_disposeConsumerTimer` is triggered before it is actually used.

This may be related to Issue #36

**Comment by pardahlman** [comment]
Mister @crillemon - thanks for reporting this! Just a few minutes before you did, I created an issue for the same problem, #50. I'll close this, and let's discuss things in #50 :+1:
