### ISSUE TITLE
Support for DNX Core 5.0

### ISSUE THREAD

**Issue by sgeef** [pardahlman/RawRabbit#56]
Are there any thoughts about supporting DNX core 5.0?

**Comment by pardahlman** [comment]
@sgeef Yes there are. At the moment we are limited by the fact that the official `RabbitMQ.Client` does not have support for it. As soon as https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/148 is closed we'll add all the Core runtimes.

**Comment by njasm** [comment]
:+1:

**Comment by robvanpamel** [comment]
Is there already more news when this is going to ship to RawRabbit? We are starting up a project in .NET Core 5.0 and we need this to make it work on non-windows OS...

**Comment by pardahlman** [comment]
@robvanpamel `RawRabbit` is depending on the official `RabbitMQ.Client` and their issue for moving to dotnet core (https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/148) is still open. All .NET clients rely on the official RabbitMq.Client library, so the same problem apply for all the different clients.

There are some unofficial ports to support dotnet core out there, but it does not make sense for RawRabbit to rely on them as they are (AFAIK)  poorly tested and not production code. Besides, the RabbitMQ team has announced that they will do a complete re-write of their client for dotnet core.

There are no easy ways to get any .NET client to run on dotnet core at the moment. What you could do is fork RawRabbit, pick one of the unofficial ports for RabbitMQ.Client, build it and use those binaries in your clone of RawRabbit. You can still leverage the vNext extensions for RawRabbit with DI, Logging and configuration etc. Then, at a later point when the official client supports dotnet core, RawRabbit will be released with a version that supports that, too and you can replace the temporary build of RawRabbit with the official one.

I will try to hold the public APIs of RawRabbit intact when the official clients supports dotnet, but if they radically change their API that might reflect in changes in RawRabbit's API, too.

Hope this helps!

**Comment by pardahlman** [comment]
Great news, the latest release of `RawRabbit` (1.9.4) now has [been released as a pre release](https://github.com/pardahlman/RawRabbit/releases/tag/1.9.4-dotnet-core) that supports .NET Core 1.0. Source code is available in the [`dotnet-core` branch](https://github.com/pardahlman/RawRabbit/tree/dotnet-core).

For installing though NuGet, use the following command

```
PM> Install-Package RawRabbit -Version 1.9.4-dotnetcore -Pre 
```
