### ISSUE TITLE
LightInject Support

### ISSUE THREAD

**Issue by Rajivhost** [pardahlman/RawRabbit#78]
Hi,
Can we have the [LightInject](http://www.lightinject.net/) IoC Container support?

**Comment by pardahlman** [comment]
@Rajivhost excelent idea :+1:. I'm currently working to complete [milestone `1.9.0`](https://github.com/pardahlman/RawRabbit/milestones/1.9.0) and next up are some neat features I have in mind. You are more than welcome to implement the LightInject support and create a Pull Request for it.
