### ISSUE TITLE
Does RawRabbit runs on DNX Core 5.0 (.Net Core) ?

### ISSUE THREAD

**Issue by viorelabrudan** [pardahlman/RawRabbit#82]
We are working on an .NET Core REST API project and we need to integrate a RabbitMQ client for bus messaging. I've tried to add the RawRabbit vNext package from nuget add it crashes, saying that there is no support for DNX Core 5.0
See the attached picture
![rawrabbit_netcore](https://cloud.githubusercontent.com/assets/12458045/15097233/74f7199c-151d-11e6-8452-3762199dc7ea.png)

So for the moment RawRabbit vNext doesn't work for .Net Core (DNX Core 5.0) ?

PS: I saw that there is a issue reported by you on RabbitMQ Client and you say that after it is closed we will have RawRabbit vNext running on .NET Core, correct?
As far as I google it to get some info for the moment there is no RabbitMQ client running for .Net Core (DNX Core 5.0) ?

Thanks in advance for your answers

**Comment by pardahlman** [comment]
Hi @viorelabrudan, thanks for reporting this. The  short answer is: no, not at the moment.  The main reason is that `RawRabbit` is dependent on the underlying (official) `RabbitMQ.Client`, which does not support .NET Core. As soon as it does, we'll have support within hours ;)

You can read more about this in #56, where options are proposed, too.
