### ISSUE TITLE
Remove MessageContext when not in use

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/RawRabbit#93]

**Comment by mrfamazing** [comment]
Is the goal here to make RawRabbit more polyglot and a little more open to messages from any publisher/subscriber? I am trying to use RR with a system has other clients that might pub/sub. Message context is one of the things that I am running into trying to send a message from another system. It's a little more complex then just adding a new serializer to consume messages from elsewhere, if impossible at this time. If this isn't the goal of RawRabbit, then you can disregard this, otherwise that would be a great path to go down.

**Comment by pardahlman** [comment]
@mrfamazing sorry for not decorating this ticket with description. This ticket is in fact more of a note-to-self; I want to make sure to dispose internal resources (MessageContext caches for message chaining).

However, making `RawRabbit` compatible with clients from other libraries and languages should not be a problem. After all, messages are serialized to json by default and headers are provided as expected :+1: . The framework itself is very modular, and it is pretty straight forward to register your own implementation of say `IMessageContextProvider` or `IBasicPropertiesProvider` etc. From the top of my head there are two things that might need to be tweaked:

-  The base class for the message context provider, [`MessageContextProviderBase`](https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit/Context/Provider/MessageContextProviderBase.cs#L25), and particular the method `ExtractContext` assumes that the header is not null. A null check that bailes out with a new `TMessageContext`, should be enough to get the message to the handler.
- Perhapes make adjustment to the registered `JsonSerializer` . Json.Net is configured to serialize `$type` information, which clients that uses other message serialisers than Json.Net might not like.

I'm currently working with support for .NET Core #99 #102, but as soon as I'm done I'll look closer at this. Let me know if you're making any progress!

**Comment by pardahlman** [comment]
Hi again @mrfamazing!

Just letting you know that I've added a specific ticket #103 for supporting handling of messages without context, headers or... anything, really except a valid json body that is deserializable to the class used in the subscriber. Check [the `PublishAndSubscribeTests.cs`](https://github.com/pardahlman/RawRabbit/blob/stable/test/RawRabbit.IntegrationTests/SimpleUse/PublishAndSubscribeTests.cs#L306]
). This will be able in `RawRabbit` version `1.10.0`, which will be released soon. If you can't wait, you should be able to implement the changes from commit adbfcfe yourself.

**Comment by mrfamazing** [comment]
Thanks for the info @pardahlman ! In my current scenario, ended up only needing to publish from .NET to XYZ, so there isn't an issue. But yes  [#103](https://github.com/pardahlman/RawRabbit/issues/103) is exactly what I had in mind, awesome work on this library!

**Comment by pardahlman** [comment]
No problemo, and thanks for the feedback :+1:

**Comment by pardahlman** [comment]
This ticket will be fixed by #125
