### ISSUE TITLE
Support for topic based routing

### ISSUE THREAD

**Issue by codedevote** [pardahlman/RawRabbit#97]
Does RawRabbit support topic exchanges and pattern matching? I surfed a little through the docs and code, but found nothing related. Is this on your roadmap for a future version?

**Comment by pardahlman** [comment]
It sure does. In fact, the default behaviour of `RawRabbit` is to create new exchanges as Topic Exchanges. This is just the default, users can configure _just about anything_. Here's a code snippet from the README

```csharp
subscriber.SubscribeAsync<BasicMessage>(async (msg, i) =>
{
  //do stuff..
}, cfg => cfg
  .WithRoutingKey("*.topic.queue")
  .WithPrefetchCount(1)
  .WithNoAck()
  .WithQueue(queue =>
    queue
      .WithName("first.topic.queue")
      .WithArgument("x-dead-letter-exchange", "dead_letter_exchange"))
  .WithExchange(exchange =>
    exchange
      .WithType(ExchangeType.Topic)
      .WithAutoDelete()
      .WithName("raw_exchange"))
  );
```

For more information, check out the [`TopicExchangeTests.cs`](https://github.com/pardahlman/RawRabbit/blob/stable/test/RawRabbit.IntegrationTests/SimpleUse/TopicExchangeTests.cs) in this repo.

**Comment by codedevote** [comment]
Awesome, thanks for pointing me in the right direction.
