### ISSUE TITLE
Latest version of RabitMQ.Client breaking changes

### ISSUE THREAD

**Issue by mrfamazing** [pardahlman/RawRabbit#98]
Seems that the package being called out in the project is no longer available for the dotnetcore branch.

**Comment by pardahlman** [comment]
@mrfamazing thanks for bringing this to my attention. `RabbitMQ.Client` version 4.0 has been released as rc-1. The RawRabbit client will be updated accordingly :ok_hand:

**Comment by pardahlman** [comment]
@mrfamazing great news. Version `1.9.4.1-dotnet` of `RawRabbit` (as well as `RawRabbit.vNext` and `RawRabbit.Extensions`) have just been released. It targets the RC1 version of `RabbitMQ.Client`. Don't forget to add https://ci.appveyor.com/nuget/rabbitmq-dotnet-client-ci to your list of NuGet feeds.

Good luck!
